package com.debug.mybatis.mapper;

import com.debug.mybatis.entity.FctExzonedetailstatus;

public interface FctExzonedetailstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONEDETAILSTATUS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONEDETAILSTATUS
     *
     * @mbggenerated
     */
    int insert(FctExzonedetailstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONEDETAILSTATUS
     *
     * @mbggenerated
     */
    int insertSelective(FctExzonedetailstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONEDETAILSTATUS
     *
     * @mbggenerated
     */
    FctExzonedetailstatus selectByPrimaryKey(Long autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONEDETAILSTATUS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FctExzonedetailstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONEDETAILSTATUS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FctExzonedetailstatus record);
}