package com.debug.mybatis.mapper;

import com.debug.mybatis.entity.FctExzonestatus;

public interface FctExzonestatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONESTATUS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONESTATUS
     *
     * @mbggenerated
     */
    int insert(FctExzonestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONESTATUS
     *
     * @mbggenerated
     */
    int insertSelective(FctExzonestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONESTATUS
     *
     * @mbggenerated
     */
    FctExzonestatus selectByPrimaryKey(Long autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONESTATUS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FctExzonestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_EXZONESTATUS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FctExzonestatus record);
}