package com.debug.mybatis.mapper;

import com.debug.mybatis.entity.FctWorkguidestage;

public interface FctWorkguidestageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_WORKGUIDESTAGE
     *
     * @mbggenerated
     */
    int insert(FctWorkguidestage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FCT_WORKGUIDESTAGE
     *
     * @mbggenerated
     */
    int insertSelective(FctWorkguidestage record);
}