package com.debug.mybatis.mapper;

import com.debug.mybatis.entity.OrgExzone;

public interface OrgExzoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORG_EXZONE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORG_EXZONE
     *
     * @mbggenerated
     */
    int insert(OrgExzone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORG_EXZONE
     *
     * @mbggenerated
     */
    int insertSelective(OrgExzone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORG_EXZONE
     *
     * @mbggenerated
     */
    OrgExzone selectByPrimaryKey(Long autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORG_EXZONE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgExzone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORG_EXZONE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgExzone record);
}