server:
    port: 5555
spring:
    application:
        name: client
eureka:
    instance:
        # 采用IP注册
        prefer-ip-address: true
        # 定义实例ID格式
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
    client:
        service-url:
            defaultZone: http://showme:123321@localhost:2222/eureka