package com.debug.mybatis.entity;

import java.math.BigDecimal;

public class FctDeclaration {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.AUTOID
     *
     * @mbggenerated
     */
    private Long autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SYS_ORG
     *
     * @mbggenerated
     */
    private Long sysOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    private String sysCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    private String sysModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SYS_CREATOR
     *
     * @mbggenerated
     */
    private String sysCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SYS_MODIFIER
     *
     * @mbggenerated
     */
    private String sysModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.FLAG
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.IDEFINE1
     *
     * @mbggenerated
     */
    private Integer idefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.IDEFINE2
     *
     * @mbggenerated
     */
    private Integer idefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.IDEFINE3
     *
     * @mbggenerated
     */
    private Integer idefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.IDEFINE4
     *
     * @mbggenerated
     */
    private Integer idefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.IDEFINE5
     *
     * @mbggenerated
     */
    private Integer idefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.FDEFINE1
     *
     * @mbggenerated
     */
    private Double fdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.FDEFINE2
     *
     * @mbggenerated
     */
    private Double fdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.FDEFINE3
     *
     * @mbggenerated
     */
    private Double fdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.FDEFINE4
     *
     * @mbggenerated
     */
    private Double fdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.FDEFINE5
     *
     * @mbggenerated
     */
    private Double fdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SDEFINE1
     *
     * @mbggenerated
     */
    private String sdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SDEFINE2
     *
     * @mbggenerated
     */
    private String sdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SDEFINE3
     *
     * @mbggenerated
     */
    private String sdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SDEFINE4
     *
     * @mbggenerated
     */
    private String sdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SDEFINE5
     *
     * @mbggenerated
     */
    private String sdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.ATTACH
     *
     * @mbggenerated
     */
    private Long attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.TASK
     *
     * @mbggenerated
     */
    private Long task;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.BYPERSON
     *
     * @mbggenerated
     */
    private Boolean byperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.QTY
     *
     * @mbggenerated
     */
    private BigDecimal qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.QTYFORDECLARATION
     *
     * @mbggenerated
     */
    private BigDecimal qtyfordeclaration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.DECLARATIONUNIT
     *
     * @mbggenerated
     */
    private String declarationunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.RATE
     *
     * @mbggenerated
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.DECLAREFOR
     *
     * @mbggenerated
     */
    private Integer declarefor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.WORKUNIT
     *
     * @mbggenerated
     */
    private Long workunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.EMPLOYEE
     *
     * @mbggenerated
     */
    private Long employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.DATE
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.STARTTIME
     *
     * @mbggenerated
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.ENDTIME
     *
     * @mbggenerated
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.TIMECONSUMING
     *
     * @mbggenerated
     */
    private BigDecimal timeconsuming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.TAG
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.BASERATE
     *
     * @mbggenerated
     */
    private BigDecimal baserate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.PARTID
     *
     * @mbggenerated
     */
    private Long partid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.PARTCODE
     *
     * @mbggenerated
     */
    private String partcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.PARTNAME
     *
     * @mbggenerated
     */
    private String partname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.PARTSTD
     *
     * @mbggenerated
     */
    private String partstd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.OPID
     *
     * @mbggenerated
     */
    private Long opid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.OPCODE
     *
     * @mbggenerated
     */
    private String opcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.OPDESC
     *
     * @mbggenerated
     */
    private String opdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.LOCK
     *
     * @mbggenerated
     */
    private Boolean lock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.DEPARTMENTNAME
     *
     * @mbggenerated
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.QTYFORSCRAP
     *
     * @mbggenerated
     */
    private BigDecimal qtyforscrap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.MATERIEL
     *
     * @mbggenerated
     */
    private String materiel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.STAGE
     *
     * @mbggenerated
     */
    private Long stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.PRICE
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.WORKUNITTYPE
     *
     * @mbggenerated
     */
    private Integer workunittype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.AVERAGE
     *
     * @mbggenerated
     */
    private Boolean average;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.THUMBNAIL
     *
     * @mbggenerated
     */
    private String thumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.BADPRODUCTSCAUSE
     *
     * @mbggenerated
     */
    private String badproductscause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.QTYFORBADPRODUCTS
     *
     * @mbggenerated
     */
    private BigDecimal qtyforbadproducts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.SCRPCAUSE
     *
     * @mbggenerated
     */
    private String scrpcause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.MACHINECODE
     *
     * @mbggenerated
     */
    private String machinecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.APPROVEYN
     *
     * @mbggenerated
     */
    private String approveyn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.COLOR
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.MOCODE
     *
     * @mbggenerated
     */
    private String mocode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.TRACECODE
     *
     * @mbggenerated
     */
    private String tracecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.CARRYQTY
     *
     * @mbggenerated
     */
    private BigDecimal carryqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.FURNACENUM
     *
     * @mbggenerated
     */
    private String furnacenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.BATCHNUM
     *
     * @mbggenerated
     */
    private String batchnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_DECLARATION.LINE
     *
     * @mbggenerated
     */
    private Integer line;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.AUTOID
     *
     * @return the value of FCT_DECLARATION.AUTOID
     *
     * @mbggenerated
     */
    public Long getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.AUTOID
     *
     * @param autoid the value for FCT_DECLARATION.AUTOID
     *
     * @mbggenerated
     */
    public void setAutoid(Long autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SYS_ORG
     *
     * @return the value of FCT_DECLARATION.SYS_ORG
     *
     * @mbggenerated
     */
    public Long getSysOrg() {
        return sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SYS_ORG
     *
     * @param sysOrg the value for FCT_DECLARATION.SYS_ORG
     *
     * @mbggenerated
     */
    public void setSysOrg(Long sysOrg) {
        this.sysOrg = sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SYS_CREATE_DATE
     *
     * @return the value of FCT_DECLARATION.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public String getSysCreateDate() {
        return sysCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SYS_CREATE_DATE
     *
     * @param sysCreateDate the value for FCT_DECLARATION.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setSysCreateDate(String sysCreateDate) {
        this.sysCreateDate = sysCreateDate == null ? null : sysCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SYS_MODIFY_DATE
     *
     * @return the value of FCT_DECLARATION.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public String getSysModifyDate() {
        return sysModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SYS_MODIFY_DATE
     *
     * @param sysModifyDate the value for FCT_DECLARATION.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setSysModifyDate(String sysModifyDate) {
        this.sysModifyDate = sysModifyDate == null ? null : sysModifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SYS_CREATOR
     *
     * @return the value of FCT_DECLARATION.SYS_CREATOR
     *
     * @mbggenerated
     */
    public String getSysCreator() {
        return sysCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SYS_CREATOR
     *
     * @param sysCreator the value for FCT_DECLARATION.SYS_CREATOR
     *
     * @mbggenerated
     */
    public void setSysCreator(String sysCreator) {
        this.sysCreator = sysCreator == null ? null : sysCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SYS_MODIFIER
     *
     * @return the value of FCT_DECLARATION.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public String getSysModifier() {
        return sysModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SYS_MODIFIER
     *
     * @param sysModifier the value for FCT_DECLARATION.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public void setSysModifier(String sysModifier) {
        this.sysModifier = sysModifier == null ? null : sysModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.FLAG
     *
     * @return the value of FCT_DECLARATION.FLAG
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.FLAG
     *
     * @param flag the value for FCT_DECLARATION.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.IDEFINE1
     *
     * @return the value of FCT_DECLARATION.IDEFINE1
     *
     * @mbggenerated
     */
    public Integer getIdefine1() {
        return idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.IDEFINE1
     *
     * @param idefine1 the value for FCT_DECLARATION.IDEFINE1
     *
     * @mbggenerated
     */
    public void setIdefine1(Integer idefine1) {
        this.idefine1 = idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.IDEFINE2
     *
     * @return the value of FCT_DECLARATION.IDEFINE2
     *
     * @mbggenerated
     */
    public Integer getIdefine2() {
        return idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.IDEFINE2
     *
     * @param idefine2 the value for FCT_DECLARATION.IDEFINE2
     *
     * @mbggenerated
     */
    public void setIdefine2(Integer idefine2) {
        this.idefine2 = idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.IDEFINE3
     *
     * @return the value of FCT_DECLARATION.IDEFINE3
     *
     * @mbggenerated
     */
    public Integer getIdefine3() {
        return idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.IDEFINE3
     *
     * @param idefine3 the value for FCT_DECLARATION.IDEFINE3
     *
     * @mbggenerated
     */
    public void setIdefine3(Integer idefine3) {
        this.idefine3 = idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.IDEFINE4
     *
     * @return the value of FCT_DECLARATION.IDEFINE4
     *
     * @mbggenerated
     */
    public Integer getIdefine4() {
        return idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.IDEFINE4
     *
     * @param idefine4 the value for FCT_DECLARATION.IDEFINE4
     *
     * @mbggenerated
     */
    public void setIdefine4(Integer idefine4) {
        this.idefine4 = idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.IDEFINE5
     *
     * @return the value of FCT_DECLARATION.IDEFINE5
     *
     * @mbggenerated
     */
    public Integer getIdefine5() {
        return idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.IDEFINE5
     *
     * @param idefine5 the value for FCT_DECLARATION.IDEFINE5
     *
     * @mbggenerated
     */
    public void setIdefine5(Integer idefine5) {
        this.idefine5 = idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.FDEFINE1
     *
     * @return the value of FCT_DECLARATION.FDEFINE1
     *
     * @mbggenerated
     */
    public Double getFdefine1() {
        return fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.FDEFINE1
     *
     * @param fdefine1 the value for FCT_DECLARATION.FDEFINE1
     *
     * @mbggenerated
     */
    public void setFdefine1(Double fdefine1) {
        this.fdefine1 = fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.FDEFINE2
     *
     * @return the value of FCT_DECLARATION.FDEFINE2
     *
     * @mbggenerated
     */
    public Double getFdefine2() {
        return fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.FDEFINE2
     *
     * @param fdefine2 the value for FCT_DECLARATION.FDEFINE2
     *
     * @mbggenerated
     */
    public void setFdefine2(Double fdefine2) {
        this.fdefine2 = fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.FDEFINE3
     *
     * @return the value of FCT_DECLARATION.FDEFINE3
     *
     * @mbggenerated
     */
    public Double getFdefine3() {
        return fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.FDEFINE3
     *
     * @param fdefine3 the value for FCT_DECLARATION.FDEFINE3
     *
     * @mbggenerated
     */
    public void setFdefine3(Double fdefine3) {
        this.fdefine3 = fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.FDEFINE4
     *
     * @return the value of FCT_DECLARATION.FDEFINE4
     *
     * @mbggenerated
     */
    public Double getFdefine4() {
        return fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.FDEFINE4
     *
     * @param fdefine4 the value for FCT_DECLARATION.FDEFINE4
     *
     * @mbggenerated
     */
    public void setFdefine4(Double fdefine4) {
        this.fdefine4 = fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.FDEFINE5
     *
     * @return the value of FCT_DECLARATION.FDEFINE5
     *
     * @mbggenerated
     */
    public Double getFdefine5() {
        return fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.FDEFINE5
     *
     * @param fdefine5 the value for FCT_DECLARATION.FDEFINE5
     *
     * @mbggenerated
     */
    public void setFdefine5(Double fdefine5) {
        this.fdefine5 = fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SDEFINE1
     *
     * @return the value of FCT_DECLARATION.SDEFINE1
     *
     * @mbggenerated
     */
    public String getSdefine1() {
        return sdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SDEFINE1
     *
     * @param sdefine1 the value for FCT_DECLARATION.SDEFINE1
     *
     * @mbggenerated
     */
    public void setSdefine1(String sdefine1) {
        this.sdefine1 = sdefine1 == null ? null : sdefine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SDEFINE2
     *
     * @return the value of FCT_DECLARATION.SDEFINE2
     *
     * @mbggenerated
     */
    public String getSdefine2() {
        return sdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SDEFINE2
     *
     * @param sdefine2 the value for FCT_DECLARATION.SDEFINE2
     *
     * @mbggenerated
     */
    public void setSdefine2(String sdefine2) {
        this.sdefine2 = sdefine2 == null ? null : sdefine2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SDEFINE3
     *
     * @return the value of FCT_DECLARATION.SDEFINE3
     *
     * @mbggenerated
     */
    public String getSdefine3() {
        return sdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SDEFINE3
     *
     * @param sdefine3 the value for FCT_DECLARATION.SDEFINE3
     *
     * @mbggenerated
     */
    public void setSdefine3(String sdefine3) {
        this.sdefine3 = sdefine3 == null ? null : sdefine3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SDEFINE4
     *
     * @return the value of FCT_DECLARATION.SDEFINE4
     *
     * @mbggenerated
     */
    public String getSdefine4() {
        return sdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SDEFINE4
     *
     * @param sdefine4 the value for FCT_DECLARATION.SDEFINE4
     *
     * @mbggenerated
     */
    public void setSdefine4(String sdefine4) {
        this.sdefine4 = sdefine4 == null ? null : sdefine4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SDEFINE5
     *
     * @return the value of FCT_DECLARATION.SDEFINE5
     *
     * @mbggenerated
     */
    public String getSdefine5() {
        return sdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SDEFINE5
     *
     * @param sdefine5 the value for FCT_DECLARATION.SDEFINE5
     *
     * @mbggenerated
     */
    public void setSdefine5(String sdefine5) {
        this.sdefine5 = sdefine5 == null ? null : sdefine5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.ATTACH
     *
     * @return the value of FCT_DECLARATION.ATTACH
     *
     * @mbggenerated
     */
    public Long getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.ATTACH
     *
     * @param attach the value for FCT_DECLARATION.ATTACH
     *
     * @mbggenerated
     */
    public void setAttach(Long attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.TASK
     *
     * @return the value of FCT_DECLARATION.TASK
     *
     * @mbggenerated
     */
    public Long getTask() {
        return task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.TASK
     *
     * @param task the value for FCT_DECLARATION.TASK
     *
     * @mbggenerated
     */
    public void setTask(Long task) {
        this.task = task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.BYPERSON
     *
     * @return the value of FCT_DECLARATION.BYPERSON
     *
     * @mbggenerated
     */
    public Boolean getByperson() {
        return byperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.BYPERSON
     *
     * @param byperson the value for FCT_DECLARATION.BYPERSON
     *
     * @mbggenerated
     */
    public void setByperson(Boolean byperson) {
        this.byperson = byperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.QTY
     *
     * @return the value of FCT_DECLARATION.QTY
     *
     * @mbggenerated
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.QTY
     *
     * @param qty the value for FCT_DECLARATION.QTY
     *
     * @mbggenerated
     */
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.QTYFORDECLARATION
     *
     * @return the value of FCT_DECLARATION.QTYFORDECLARATION
     *
     * @mbggenerated
     */
    public BigDecimal getQtyfordeclaration() {
        return qtyfordeclaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.QTYFORDECLARATION
     *
     * @param qtyfordeclaration the value for FCT_DECLARATION.QTYFORDECLARATION
     *
     * @mbggenerated
     */
    public void setQtyfordeclaration(BigDecimal qtyfordeclaration) {
        this.qtyfordeclaration = qtyfordeclaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.UNIT
     *
     * @return the value of FCT_DECLARATION.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.UNIT
     *
     * @param unit the value for FCT_DECLARATION.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.DECLARATIONUNIT
     *
     * @return the value of FCT_DECLARATION.DECLARATIONUNIT
     *
     * @mbggenerated
     */
    public String getDeclarationunit() {
        return declarationunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.DECLARATIONUNIT
     *
     * @param declarationunit the value for FCT_DECLARATION.DECLARATIONUNIT
     *
     * @mbggenerated
     */
    public void setDeclarationunit(String declarationunit) {
        this.declarationunit = declarationunit == null ? null : declarationunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.RATE
     *
     * @return the value of FCT_DECLARATION.RATE
     *
     * @mbggenerated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.RATE
     *
     * @param rate the value for FCT_DECLARATION.RATE
     *
     * @mbggenerated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.DECLAREFOR
     *
     * @return the value of FCT_DECLARATION.DECLAREFOR
     *
     * @mbggenerated
     */
    public Integer getDeclarefor() {
        return declarefor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.DECLAREFOR
     *
     * @param declarefor the value for FCT_DECLARATION.DECLAREFOR
     *
     * @mbggenerated
     */
    public void setDeclarefor(Integer declarefor) {
        this.declarefor = declarefor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.WORKUNIT
     *
     * @return the value of FCT_DECLARATION.WORKUNIT
     *
     * @mbggenerated
     */
    public Long getWorkunit() {
        return workunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.WORKUNIT
     *
     * @param workunit the value for FCT_DECLARATION.WORKUNIT
     *
     * @mbggenerated
     */
    public void setWorkunit(Long workunit) {
        this.workunit = workunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.EMPLOYEE
     *
     * @return the value of FCT_DECLARATION.EMPLOYEE
     *
     * @mbggenerated
     */
    public Long getEmployee() {
        return employee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.EMPLOYEE
     *
     * @param employee the value for FCT_DECLARATION.EMPLOYEE
     *
     * @mbggenerated
     */
    public void setEmployee(Long employee) {
        this.employee = employee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.DATE
     *
     * @return the value of FCT_DECLARATION.DATE
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.DATE
     *
     * @param date the value for FCT_DECLARATION.DATE
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.STATUS
     *
     * @return the value of FCT_DECLARATION.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.STATUS
     *
     * @param status the value for FCT_DECLARATION.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.STARTTIME
     *
     * @return the value of FCT_DECLARATION.STARTTIME
     *
     * @mbggenerated
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.STARTTIME
     *
     * @param starttime the value for FCT_DECLARATION.STARTTIME
     *
     * @mbggenerated
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.ENDTIME
     *
     * @return the value of FCT_DECLARATION.ENDTIME
     *
     * @mbggenerated
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.ENDTIME
     *
     * @param endtime the value for FCT_DECLARATION.ENDTIME
     *
     * @mbggenerated
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.TIMECONSUMING
     *
     * @return the value of FCT_DECLARATION.TIMECONSUMING
     *
     * @mbggenerated
     */
    public BigDecimal getTimeconsuming() {
        return timeconsuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.TIMECONSUMING
     *
     * @param timeconsuming the value for FCT_DECLARATION.TIMECONSUMING
     *
     * @mbggenerated
     */
    public void setTimeconsuming(BigDecimal timeconsuming) {
        this.timeconsuming = timeconsuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.TAG
     *
     * @return the value of FCT_DECLARATION.TAG
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.TAG
     *
     * @param tag the value for FCT_DECLARATION.TAG
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.BASERATE
     *
     * @return the value of FCT_DECLARATION.BASERATE
     *
     * @mbggenerated
     */
    public BigDecimal getBaserate() {
        return baserate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.BASERATE
     *
     * @param baserate the value for FCT_DECLARATION.BASERATE
     *
     * @mbggenerated
     */
    public void setBaserate(BigDecimal baserate) {
        this.baserate = baserate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.PARTID
     *
     * @return the value of FCT_DECLARATION.PARTID
     *
     * @mbggenerated
     */
    public Long getPartid() {
        return partid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.PARTID
     *
     * @param partid the value for FCT_DECLARATION.PARTID
     *
     * @mbggenerated
     */
    public void setPartid(Long partid) {
        this.partid = partid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.PARTCODE
     *
     * @return the value of FCT_DECLARATION.PARTCODE
     *
     * @mbggenerated
     */
    public String getPartcode() {
        return partcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.PARTCODE
     *
     * @param partcode the value for FCT_DECLARATION.PARTCODE
     *
     * @mbggenerated
     */
    public void setPartcode(String partcode) {
        this.partcode = partcode == null ? null : partcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.PARTNAME
     *
     * @return the value of FCT_DECLARATION.PARTNAME
     *
     * @mbggenerated
     */
    public String getPartname() {
        return partname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.PARTNAME
     *
     * @param partname the value for FCT_DECLARATION.PARTNAME
     *
     * @mbggenerated
     */
    public void setPartname(String partname) {
        this.partname = partname == null ? null : partname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.PARTSTD
     *
     * @return the value of FCT_DECLARATION.PARTSTD
     *
     * @mbggenerated
     */
    public String getPartstd() {
        return partstd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.PARTSTD
     *
     * @param partstd the value for FCT_DECLARATION.PARTSTD
     *
     * @mbggenerated
     */
    public void setPartstd(String partstd) {
        this.partstd = partstd == null ? null : partstd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.OPID
     *
     * @return the value of FCT_DECLARATION.OPID
     *
     * @mbggenerated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.OPID
     *
     * @param opid the value for FCT_DECLARATION.OPID
     *
     * @mbggenerated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.OPCODE
     *
     * @return the value of FCT_DECLARATION.OPCODE
     *
     * @mbggenerated
     */
    public String getOpcode() {
        return opcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.OPCODE
     *
     * @param opcode the value for FCT_DECLARATION.OPCODE
     *
     * @mbggenerated
     */
    public void setOpcode(String opcode) {
        this.opcode = opcode == null ? null : opcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.OPDESC
     *
     * @return the value of FCT_DECLARATION.OPDESC
     *
     * @mbggenerated
     */
    public String getOpdesc() {
        return opdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.OPDESC
     *
     * @param opdesc the value for FCT_DECLARATION.OPDESC
     *
     * @mbggenerated
     */
    public void setOpdesc(String opdesc) {
        this.opdesc = opdesc == null ? null : opdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.LOCK
     *
     * @return the value of FCT_DECLARATION.LOCK
     *
     * @mbggenerated
     */
    public Boolean getLock() {
        return lock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.LOCK
     *
     * @param lock the value for FCT_DECLARATION.LOCK
     *
     * @mbggenerated
     */
    public void setLock(Boolean lock) {
        this.lock = lock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.DEPARTMENTNAME
     *
     * @return the value of FCT_DECLARATION.DEPARTMENTNAME
     *
     * @mbggenerated
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.DEPARTMENTNAME
     *
     * @param departmentname the value for FCT_DECLARATION.DEPARTMENTNAME
     *
     * @mbggenerated
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.QTYFORSCRAP
     *
     * @return the value of FCT_DECLARATION.QTYFORSCRAP
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforscrap() {
        return qtyforscrap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.QTYFORSCRAP
     *
     * @param qtyforscrap the value for FCT_DECLARATION.QTYFORSCRAP
     *
     * @mbggenerated
     */
    public void setQtyforscrap(BigDecimal qtyforscrap) {
        this.qtyforscrap = qtyforscrap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.MATERIEL
     *
     * @return the value of FCT_DECLARATION.MATERIEL
     *
     * @mbggenerated
     */
    public String getMateriel() {
        return materiel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.MATERIEL
     *
     * @param materiel the value for FCT_DECLARATION.MATERIEL
     *
     * @mbggenerated
     */
    public void setMateriel(String materiel) {
        this.materiel = materiel == null ? null : materiel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.STAGE
     *
     * @return the value of FCT_DECLARATION.STAGE
     *
     * @mbggenerated
     */
    public Long getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.STAGE
     *
     * @param stage the value for FCT_DECLARATION.STAGE
     *
     * @mbggenerated
     */
    public void setStage(Long stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.PRICE
     *
     * @return the value of FCT_DECLARATION.PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.PRICE
     *
     * @param price the value for FCT_DECLARATION.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.WORKUNITTYPE
     *
     * @return the value of FCT_DECLARATION.WORKUNITTYPE
     *
     * @mbggenerated
     */
    public Integer getWorkunittype() {
        return workunittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.WORKUNITTYPE
     *
     * @param workunittype the value for FCT_DECLARATION.WORKUNITTYPE
     *
     * @mbggenerated
     */
    public void setWorkunittype(Integer workunittype) {
        this.workunittype = workunittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.AVERAGE
     *
     * @return the value of FCT_DECLARATION.AVERAGE
     *
     * @mbggenerated
     */
    public Boolean getAverage() {
        return average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.AVERAGE
     *
     * @param average the value for FCT_DECLARATION.AVERAGE
     *
     * @mbggenerated
     */
    public void setAverage(Boolean average) {
        this.average = average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.THUMBNAIL
     *
     * @return the value of FCT_DECLARATION.THUMBNAIL
     *
     * @mbggenerated
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.THUMBNAIL
     *
     * @param thumbnail the value for FCT_DECLARATION.THUMBNAIL
     *
     * @mbggenerated
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.BADPRODUCTSCAUSE
     *
     * @return the value of FCT_DECLARATION.BADPRODUCTSCAUSE
     *
     * @mbggenerated
     */
    public String getBadproductscause() {
        return badproductscause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.BADPRODUCTSCAUSE
     *
     * @param badproductscause the value for FCT_DECLARATION.BADPRODUCTSCAUSE
     *
     * @mbggenerated
     */
    public void setBadproductscause(String badproductscause) {
        this.badproductscause = badproductscause == null ? null : badproductscause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.QTYFORBADPRODUCTS
     *
     * @return the value of FCT_DECLARATION.QTYFORBADPRODUCTS
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforbadproducts() {
        return qtyforbadproducts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.QTYFORBADPRODUCTS
     *
     * @param qtyforbadproducts the value for FCT_DECLARATION.QTYFORBADPRODUCTS
     *
     * @mbggenerated
     */
    public void setQtyforbadproducts(BigDecimal qtyforbadproducts) {
        this.qtyforbadproducts = qtyforbadproducts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.SCRPCAUSE
     *
     * @return the value of FCT_DECLARATION.SCRPCAUSE
     *
     * @mbggenerated
     */
    public String getScrpcause() {
        return scrpcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.SCRPCAUSE
     *
     * @param scrpcause the value for FCT_DECLARATION.SCRPCAUSE
     *
     * @mbggenerated
     */
    public void setScrpcause(String scrpcause) {
        this.scrpcause = scrpcause == null ? null : scrpcause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.MACHINECODE
     *
     * @return the value of FCT_DECLARATION.MACHINECODE
     *
     * @mbggenerated
     */
    public String getMachinecode() {
        return machinecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.MACHINECODE
     *
     * @param machinecode the value for FCT_DECLARATION.MACHINECODE
     *
     * @mbggenerated
     */
    public void setMachinecode(String machinecode) {
        this.machinecode = machinecode == null ? null : machinecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.APPROVEYN
     *
     * @return the value of FCT_DECLARATION.APPROVEYN
     *
     * @mbggenerated
     */
    public String getApproveyn() {
        return approveyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.APPROVEYN
     *
     * @param approveyn the value for FCT_DECLARATION.APPROVEYN
     *
     * @mbggenerated
     */
    public void setApproveyn(String approveyn) {
        this.approveyn = approveyn == null ? null : approveyn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.REMARK
     *
     * @return the value of FCT_DECLARATION.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.REMARK
     *
     * @param remark the value for FCT_DECLARATION.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.COLOR
     *
     * @return the value of FCT_DECLARATION.COLOR
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.COLOR
     *
     * @param color the value for FCT_DECLARATION.COLOR
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.NOTE
     *
     * @return the value of FCT_DECLARATION.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.NOTE
     *
     * @param note the value for FCT_DECLARATION.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.MOCODE
     *
     * @return the value of FCT_DECLARATION.MOCODE
     *
     * @mbggenerated
     */
    public String getMocode() {
        return mocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.MOCODE
     *
     * @param mocode the value for FCT_DECLARATION.MOCODE
     *
     * @mbggenerated
     */
    public void setMocode(String mocode) {
        this.mocode = mocode == null ? null : mocode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.TRACECODE
     *
     * @return the value of FCT_DECLARATION.TRACECODE
     *
     * @mbggenerated
     */
    public String getTracecode() {
        return tracecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.TRACECODE
     *
     * @param tracecode the value for FCT_DECLARATION.TRACECODE
     *
     * @mbggenerated
     */
    public void setTracecode(String tracecode) {
        this.tracecode = tracecode == null ? null : tracecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.CARRYQTY
     *
     * @return the value of FCT_DECLARATION.CARRYQTY
     *
     * @mbggenerated
     */
    public BigDecimal getCarryqty() {
        return carryqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.CARRYQTY
     *
     * @param carryqty the value for FCT_DECLARATION.CARRYQTY
     *
     * @mbggenerated
     */
    public void setCarryqty(BigDecimal carryqty) {
        this.carryqty = carryqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.FURNACENUM
     *
     * @return the value of FCT_DECLARATION.FURNACENUM
     *
     * @mbggenerated
     */
    public String getFurnacenum() {
        return furnacenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.FURNACENUM
     *
     * @param furnacenum the value for FCT_DECLARATION.FURNACENUM
     *
     * @mbggenerated
     */
    public void setFurnacenum(String furnacenum) {
        this.furnacenum = furnacenum == null ? null : furnacenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.BATCHNUM
     *
     * @return the value of FCT_DECLARATION.BATCHNUM
     *
     * @mbggenerated
     */
    public String getBatchnum() {
        return batchnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.BATCHNUM
     *
     * @param batchnum the value for FCT_DECLARATION.BATCHNUM
     *
     * @mbggenerated
     */
    public void setBatchnum(String batchnum) {
        this.batchnum = batchnum == null ? null : batchnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_DECLARATION.LINE
     *
     * @return the value of FCT_DECLARATION.LINE
     *
     * @mbggenerated
     */
    public Integer getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_DECLARATION.LINE
     *
     * @param line the value for FCT_DECLARATION.LINE
     *
     * @mbggenerated
     */
    public void setLine(Integer line) {
        this.line = line;
    }
}