package com.debug.mybatis.entity;

import java.math.BigDecimal;

public class FctExzonestatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.AUTOID
     *
     * @mbggenerated
     */
    private Long autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SYS_ORG
     *
     * @mbggenerated
     */
    private Long sysOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    private String sysCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    private String sysModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SYS_CREATOR
     *
     * @mbggenerated
     */
    private String sysCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SYS_MODIFIER
     *
     * @mbggenerated
     */
    private String sysModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.FLAG
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.IDEFINE1
     *
     * @mbggenerated
     */
    private Integer idefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.IDEFINE2
     *
     * @mbggenerated
     */
    private Integer idefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.IDEFINE3
     *
     * @mbggenerated
     */
    private Integer idefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.IDEFINE4
     *
     * @mbggenerated
     */
    private Integer idefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.IDEFINE5
     *
     * @mbggenerated
     */
    private Integer idefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.FDEFINE1
     *
     * @mbggenerated
     */
    private Double fdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.FDEFINE2
     *
     * @mbggenerated
     */
    private Double fdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.FDEFINE3
     *
     * @mbggenerated
     */
    private Double fdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.FDEFINE4
     *
     * @mbggenerated
     */
    private Double fdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.FDEFINE5
     *
     * @mbggenerated
     */
    private Double fdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SDEFINE1
     *
     * @mbggenerated
     */
    private String sdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SDEFINE2
     *
     * @mbggenerated
     */
    private String sdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SDEFINE3
     *
     * @mbggenerated
     */
    private String sdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SDEFINE4
     *
     * @mbggenerated
     */
    private String sdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.SDEFINE5
     *
     * @mbggenerated
     */
    private String sdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.ATTACH
     *
     * @mbggenerated
     */
    private Long attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.PART
     *
     * @mbggenerated
     */
    private Long part;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.MO
     *
     * @mbggenerated
     */
    private Long mo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.STAGE
     *
     * @mbggenerated
     */
    private Long stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.EXZONE
     *
     * @mbggenerated
     */
    private Long exzone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.QTYFORACCEPT
     *
     * @mbggenerated
     */
    private BigDecimal qtyforaccept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.QTYFORSCRAP
     *
     * @mbggenerated
     */
    private BigDecimal qtyforscrap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.QTYFORTRANSIT
     *
     * @mbggenerated
     */
    private BigDecimal qtyfortransit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.QTYFORPASSED
     *
     * @mbggenerated
     */
    private BigDecimal qtyforpassed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.QTYFORRELEASED
     *
     * @mbggenerated
     */
    private BigDecimal qtyforreleased;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONESTATUS.TRACECODE
     *
     * @mbggenerated
     */
    private String tracecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.AUTOID
     *
     * @return the value of FCT_EXZONESTATUS.AUTOID
     *
     * @mbggenerated
     */
    public Long getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.AUTOID
     *
     * @param autoid the value for FCT_EXZONESTATUS.AUTOID
     *
     * @mbggenerated
     */
    public void setAutoid(Long autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SYS_ORG
     *
     * @return the value of FCT_EXZONESTATUS.SYS_ORG
     *
     * @mbggenerated
     */
    public Long getSysOrg() {
        return sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SYS_ORG
     *
     * @param sysOrg the value for FCT_EXZONESTATUS.SYS_ORG
     *
     * @mbggenerated
     */
    public void setSysOrg(Long sysOrg) {
        this.sysOrg = sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SYS_CREATE_DATE
     *
     * @return the value of FCT_EXZONESTATUS.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public String getSysCreateDate() {
        return sysCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SYS_CREATE_DATE
     *
     * @param sysCreateDate the value for FCT_EXZONESTATUS.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setSysCreateDate(String sysCreateDate) {
        this.sysCreateDate = sysCreateDate == null ? null : sysCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SYS_MODIFY_DATE
     *
     * @return the value of FCT_EXZONESTATUS.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public String getSysModifyDate() {
        return sysModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SYS_MODIFY_DATE
     *
     * @param sysModifyDate the value for FCT_EXZONESTATUS.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setSysModifyDate(String sysModifyDate) {
        this.sysModifyDate = sysModifyDate == null ? null : sysModifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SYS_CREATOR
     *
     * @return the value of FCT_EXZONESTATUS.SYS_CREATOR
     *
     * @mbggenerated
     */
    public String getSysCreator() {
        return sysCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SYS_CREATOR
     *
     * @param sysCreator the value for FCT_EXZONESTATUS.SYS_CREATOR
     *
     * @mbggenerated
     */
    public void setSysCreator(String sysCreator) {
        this.sysCreator = sysCreator == null ? null : sysCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SYS_MODIFIER
     *
     * @return the value of FCT_EXZONESTATUS.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public String getSysModifier() {
        return sysModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SYS_MODIFIER
     *
     * @param sysModifier the value for FCT_EXZONESTATUS.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public void setSysModifier(String sysModifier) {
        this.sysModifier = sysModifier == null ? null : sysModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.FLAG
     *
     * @return the value of FCT_EXZONESTATUS.FLAG
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.FLAG
     *
     * @param flag the value for FCT_EXZONESTATUS.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.IDEFINE1
     *
     * @return the value of FCT_EXZONESTATUS.IDEFINE1
     *
     * @mbggenerated
     */
    public Integer getIdefine1() {
        return idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.IDEFINE1
     *
     * @param idefine1 the value for FCT_EXZONESTATUS.IDEFINE1
     *
     * @mbggenerated
     */
    public void setIdefine1(Integer idefine1) {
        this.idefine1 = idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.IDEFINE2
     *
     * @return the value of FCT_EXZONESTATUS.IDEFINE2
     *
     * @mbggenerated
     */
    public Integer getIdefine2() {
        return idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.IDEFINE2
     *
     * @param idefine2 the value for FCT_EXZONESTATUS.IDEFINE2
     *
     * @mbggenerated
     */
    public void setIdefine2(Integer idefine2) {
        this.idefine2 = idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.IDEFINE3
     *
     * @return the value of FCT_EXZONESTATUS.IDEFINE3
     *
     * @mbggenerated
     */
    public Integer getIdefine3() {
        return idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.IDEFINE3
     *
     * @param idefine3 the value for FCT_EXZONESTATUS.IDEFINE3
     *
     * @mbggenerated
     */
    public void setIdefine3(Integer idefine3) {
        this.idefine3 = idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.IDEFINE4
     *
     * @return the value of FCT_EXZONESTATUS.IDEFINE4
     *
     * @mbggenerated
     */
    public Integer getIdefine4() {
        return idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.IDEFINE4
     *
     * @param idefine4 the value for FCT_EXZONESTATUS.IDEFINE4
     *
     * @mbggenerated
     */
    public void setIdefine4(Integer idefine4) {
        this.idefine4 = idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.IDEFINE5
     *
     * @return the value of FCT_EXZONESTATUS.IDEFINE5
     *
     * @mbggenerated
     */
    public Integer getIdefine5() {
        return idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.IDEFINE5
     *
     * @param idefine5 the value for FCT_EXZONESTATUS.IDEFINE5
     *
     * @mbggenerated
     */
    public void setIdefine5(Integer idefine5) {
        this.idefine5 = idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.FDEFINE1
     *
     * @return the value of FCT_EXZONESTATUS.FDEFINE1
     *
     * @mbggenerated
     */
    public Double getFdefine1() {
        return fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.FDEFINE1
     *
     * @param fdefine1 the value for FCT_EXZONESTATUS.FDEFINE1
     *
     * @mbggenerated
     */
    public void setFdefine1(Double fdefine1) {
        this.fdefine1 = fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.FDEFINE2
     *
     * @return the value of FCT_EXZONESTATUS.FDEFINE2
     *
     * @mbggenerated
     */
    public Double getFdefine2() {
        return fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.FDEFINE2
     *
     * @param fdefine2 the value for FCT_EXZONESTATUS.FDEFINE2
     *
     * @mbggenerated
     */
    public void setFdefine2(Double fdefine2) {
        this.fdefine2 = fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.FDEFINE3
     *
     * @return the value of FCT_EXZONESTATUS.FDEFINE3
     *
     * @mbggenerated
     */
    public Double getFdefine3() {
        return fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.FDEFINE3
     *
     * @param fdefine3 the value for FCT_EXZONESTATUS.FDEFINE3
     *
     * @mbggenerated
     */
    public void setFdefine3(Double fdefine3) {
        this.fdefine3 = fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.FDEFINE4
     *
     * @return the value of FCT_EXZONESTATUS.FDEFINE4
     *
     * @mbggenerated
     */
    public Double getFdefine4() {
        return fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.FDEFINE4
     *
     * @param fdefine4 the value for FCT_EXZONESTATUS.FDEFINE4
     *
     * @mbggenerated
     */
    public void setFdefine4(Double fdefine4) {
        this.fdefine4 = fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.FDEFINE5
     *
     * @return the value of FCT_EXZONESTATUS.FDEFINE5
     *
     * @mbggenerated
     */
    public Double getFdefine5() {
        return fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.FDEFINE5
     *
     * @param fdefine5 the value for FCT_EXZONESTATUS.FDEFINE5
     *
     * @mbggenerated
     */
    public void setFdefine5(Double fdefine5) {
        this.fdefine5 = fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SDEFINE1
     *
     * @return the value of FCT_EXZONESTATUS.SDEFINE1
     *
     * @mbggenerated
     */
    public String getSdefine1() {
        return sdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SDEFINE1
     *
     * @param sdefine1 the value for FCT_EXZONESTATUS.SDEFINE1
     *
     * @mbggenerated
     */
    public void setSdefine1(String sdefine1) {
        this.sdefine1 = sdefine1 == null ? null : sdefine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SDEFINE2
     *
     * @return the value of FCT_EXZONESTATUS.SDEFINE2
     *
     * @mbggenerated
     */
    public String getSdefine2() {
        return sdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SDEFINE2
     *
     * @param sdefine2 the value for FCT_EXZONESTATUS.SDEFINE2
     *
     * @mbggenerated
     */
    public void setSdefine2(String sdefine2) {
        this.sdefine2 = sdefine2 == null ? null : sdefine2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SDEFINE3
     *
     * @return the value of FCT_EXZONESTATUS.SDEFINE3
     *
     * @mbggenerated
     */
    public String getSdefine3() {
        return sdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SDEFINE3
     *
     * @param sdefine3 the value for FCT_EXZONESTATUS.SDEFINE3
     *
     * @mbggenerated
     */
    public void setSdefine3(String sdefine3) {
        this.sdefine3 = sdefine3 == null ? null : sdefine3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SDEFINE4
     *
     * @return the value of FCT_EXZONESTATUS.SDEFINE4
     *
     * @mbggenerated
     */
    public String getSdefine4() {
        return sdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SDEFINE4
     *
     * @param sdefine4 the value for FCT_EXZONESTATUS.SDEFINE4
     *
     * @mbggenerated
     */
    public void setSdefine4(String sdefine4) {
        this.sdefine4 = sdefine4 == null ? null : sdefine4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.SDEFINE5
     *
     * @return the value of FCT_EXZONESTATUS.SDEFINE5
     *
     * @mbggenerated
     */
    public String getSdefine5() {
        return sdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.SDEFINE5
     *
     * @param sdefine5 the value for FCT_EXZONESTATUS.SDEFINE5
     *
     * @mbggenerated
     */
    public void setSdefine5(String sdefine5) {
        this.sdefine5 = sdefine5 == null ? null : sdefine5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.ATTACH
     *
     * @return the value of FCT_EXZONESTATUS.ATTACH
     *
     * @mbggenerated
     */
    public Long getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.ATTACH
     *
     * @param attach the value for FCT_EXZONESTATUS.ATTACH
     *
     * @mbggenerated
     */
    public void setAttach(Long attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.PART
     *
     * @return the value of FCT_EXZONESTATUS.PART
     *
     * @mbggenerated
     */
    public Long getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.PART
     *
     * @param part the value for FCT_EXZONESTATUS.PART
     *
     * @mbggenerated
     */
    public void setPart(Long part) {
        this.part = part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.MO
     *
     * @return the value of FCT_EXZONESTATUS.MO
     *
     * @mbggenerated
     */
    public Long getMo() {
        return mo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.MO
     *
     * @param mo the value for FCT_EXZONESTATUS.MO
     *
     * @mbggenerated
     */
    public void setMo(Long mo) {
        this.mo = mo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.STAGE
     *
     * @return the value of FCT_EXZONESTATUS.STAGE
     *
     * @mbggenerated
     */
    public Long getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.STAGE
     *
     * @param stage the value for FCT_EXZONESTATUS.STAGE
     *
     * @mbggenerated
     */
    public void setStage(Long stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.EXZONE
     *
     * @return the value of FCT_EXZONESTATUS.EXZONE
     *
     * @mbggenerated
     */
    public Long getExzone() {
        return exzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.EXZONE
     *
     * @param exzone the value for FCT_EXZONESTATUS.EXZONE
     *
     * @mbggenerated
     */
    public void setExzone(Long exzone) {
        this.exzone = exzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.QTYFORACCEPT
     *
     * @return the value of FCT_EXZONESTATUS.QTYFORACCEPT
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforaccept() {
        return qtyforaccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.QTYFORACCEPT
     *
     * @param qtyforaccept the value for FCT_EXZONESTATUS.QTYFORACCEPT
     *
     * @mbggenerated
     */
    public void setQtyforaccept(BigDecimal qtyforaccept) {
        this.qtyforaccept = qtyforaccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.QTYFORSCRAP
     *
     * @return the value of FCT_EXZONESTATUS.QTYFORSCRAP
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforscrap() {
        return qtyforscrap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.QTYFORSCRAP
     *
     * @param qtyforscrap the value for FCT_EXZONESTATUS.QTYFORSCRAP
     *
     * @mbggenerated
     */
    public void setQtyforscrap(BigDecimal qtyforscrap) {
        this.qtyforscrap = qtyforscrap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.QTYFORTRANSIT
     *
     * @return the value of FCT_EXZONESTATUS.QTYFORTRANSIT
     *
     * @mbggenerated
     */
    public BigDecimal getQtyfortransit() {
        return qtyfortransit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.QTYFORTRANSIT
     *
     * @param qtyfortransit the value for FCT_EXZONESTATUS.QTYFORTRANSIT
     *
     * @mbggenerated
     */
    public void setQtyfortransit(BigDecimal qtyfortransit) {
        this.qtyfortransit = qtyfortransit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.QTYFORPASSED
     *
     * @return the value of FCT_EXZONESTATUS.QTYFORPASSED
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforpassed() {
        return qtyforpassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.QTYFORPASSED
     *
     * @param qtyforpassed the value for FCT_EXZONESTATUS.QTYFORPASSED
     *
     * @mbggenerated
     */
    public void setQtyforpassed(BigDecimal qtyforpassed) {
        this.qtyforpassed = qtyforpassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.QTYFORRELEASED
     *
     * @return the value of FCT_EXZONESTATUS.QTYFORRELEASED
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforreleased() {
        return qtyforreleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.QTYFORRELEASED
     *
     * @param qtyforreleased the value for FCT_EXZONESTATUS.QTYFORRELEASED
     *
     * @mbggenerated
     */
    public void setQtyforreleased(BigDecimal qtyforreleased) {
        this.qtyforreleased = qtyforreleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.UNIT
     *
     * @return the value of FCT_EXZONESTATUS.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.UNIT
     *
     * @param unit the value for FCT_EXZONESTATUS.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONESTATUS.TRACECODE
     *
     * @return the value of FCT_EXZONESTATUS.TRACECODE
     *
     * @mbggenerated
     */
    public String getTracecode() {
        return tracecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONESTATUS.TRACECODE
     *
     * @param tracecode the value for FCT_EXZONESTATUS.TRACECODE
     *
     * @mbggenerated
     */
    public void setTracecode(String tracecode) {
        this.tracecode = tracecode == null ? null : tracecode.trim();
    }
}