package com.debug.mybatis.entity;

import java.math.BigDecimal;

public class FctExzonedetailstatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.AUTOID
     *
     * @mbggenerated
     */
    private Long autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SYS_ORG
     *
     * @mbggenerated
     */
    private Long sysOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    private String sysCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    private String sysModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SYS_CREATOR
     *
     * @mbggenerated
     */
    private String sysCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SYS_MODIFIER
     *
     * @mbggenerated
     */
    private String sysModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.FLAG
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.IDEFINE1
     *
     * @mbggenerated
     */
    private Integer idefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.IDEFINE2
     *
     * @mbggenerated
     */
    private Integer idefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.IDEFINE3
     *
     * @mbggenerated
     */
    private Integer idefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.IDEFINE4
     *
     * @mbggenerated
     */
    private Integer idefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.IDEFINE5
     *
     * @mbggenerated
     */
    private Integer idefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.FDEFINE1
     *
     * @mbggenerated
     */
    private Double fdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.FDEFINE2
     *
     * @mbggenerated
     */
    private Double fdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.FDEFINE3
     *
     * @mbggenerated
     */
    private Double fdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.FDEFINE4
     *
     * @mbggenerated
     */
    private Double fdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.FDEFINE5
     *
     * @mbggenerated
     */
    private Double fdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SDEFINE1
     *
     * @mbggenerated
     */
    private String sdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SDEFINE2
     *
     * @mbggenerated
     */
    private String sdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SDEFINE3
     *
     * @mbggenerated
     */
    private String sdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SDEFINE4
     *
     * @mbggenerated
     */
    private String sdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.SDEFINE5
     *
     * @mbggenerated
     */
    private String sdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.ATTACH
     *
     * @mbggenerated
     */
    private Long attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.PART
     *
     * @mbggenerated
     */
    private Long part;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.MO
     *
     * @mbggenerated
     */
    private Long mo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.WORKGUIDEDETAIL
     *
     * @mbggenerated
     */
    private Long workguidedetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.EXZONE
     *
     * @mbggenerated
     */
    private Long exzone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.QTYFORCOMPLETED
     *
     * @mbggenerated
     */
    private BigDecimal qtyforcompleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.QTYFORRECEIVED
     *
     * @mbggenerated
     */
    private BigDecimal qtyforreceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.QTYFORMERGE
     *
     * @mbggenerated
     */
    private BigDecimal qtyformerge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.QTYFORPROCESSING
     *
     * @mbggenerated
     */
    private BigDecimal qtyforprocessing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.QTYFORSKIP
     *
     * @mbggenerated
     */
    private BigDecimal qtyforskip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.QTYFORREWORK
     *
     * @mbggenerated
     */
    private BigDecimal qtyforrework;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.TRACECODE
     *
     * @mbggenerated
     */
    private String tracecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.STAGE
     *
     * @mbggenerated
     */
    private Long stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.QTYFORSUPER
     *
     * @mbggenerated
     */
    private BigDecimal qtyforsuper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_EXZONEDETAILSTATUS.QTYFORSCRAP
     *
     * @mbggenerated
     */
    private BigDecimal qtyforscrap;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.AUTOID
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.AUTOID
     *
     * @mbggenerated
     */
    public Long getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.AUTOID
     *
     * @param autoid the value for FCT_EXZONEDETAILSTATUS.AUTOID
     *
     * @mbggenerated
     */
    public void setAutoid(Long autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SYS_ORG
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SYS_ORG
     *
     * @mbggenerated
     */
    public Long getSysOrg() {
        return sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SYS_ORG
     *
     * @param sysOrg the value for FCT_EXZONEDETAILSTATUS.SYS_ORG
     *
     * @mbggenerated
     */
    public void setSysOrg(Long sysOrg) {
        this.sysOrg = sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SYS_CREATE_DATE
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public String getSysCreateDate() {
        return sysCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SYS_CREATE_DATE
     *
     * @param sysCreateDate the value for FCT_EXZONEDETAILSTATUS.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setSysCreateDate(String sysCreateDate) {
        this.sysCreateDate = sysCreateDate == null ? null : sysCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SYS_MODIFY_DATE
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public String getSysModifyDate() {
        return sysModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SYS_MODIFY_DATE
     *
     * @param sysModifyDate the value for FCT_EXZONEDETAILSTATUS.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setSysModifyDate(String sysModifyDate) {
        this.sysModifyDate = sysModifyDate == null ? null : sysModifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SYS_CREATOR
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SYS_CREATOR
     *
     * @mbggenerated
     */
    public String getSysCreator() {
        return sysCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SYS_CREATOR
     *
     * @param sysCreator the value for FCT_EXZONEDETAILSTATUS.SYS_CREATOR
     *
     * @mbggenerated
     */
    public void setSysCreator(String sysCreator) {
        this.sysCreator = sysCreator == null ? null : sysCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SYS_MODIFIER
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public String getSysModifier() {
        return sysModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SYS_MODIFIER
     *
     * @param sysModifier the value for FCT_EXZONEDETAILSTATUS.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public void setSysModifier(String sysModifier) {
        this.sysModifier = sysModifier == null ? null : sysModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.FLAG
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.FLAG
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.FLAG
     *
     * @param flag the value for FCT_EXZONEDETAILSTATUS.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE1
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.IDEFINE1
     *
     * @mbggenerated
     */
    public Integer getIdefine1() {
        return idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE1
     *
     * @param idefine1 the value for FCT_EXZONEDETAILSTATUS.IDEFINE1
     *
     * @mbggenerated
     */
    public void setIdefine1(Integer idefine1) {
        this.idefine1 = idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE2
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.IDEFINE2
     *
     * @mbggenerated
     */
    public Integer getIdefine2() {
        return idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE2
     *
     * @param idefine2 the value for FCT_EXZONEDETAILSTATUS.IDEFINE2
     *
     * @mbggenerated
     */
    public void setIdefine2(Integer idefine2) {
        this.idefine2 = idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE3
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.IDEFINE3
     *
     * @mbggenerated
     */
    public Integer getIdefine3() {
        return idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE3
     *
     * @param idefine3 the value for FCT_EXZONEDETAILSTATUS.IDEFINE3
     *
     * @mbggenerated
     */
    public void setIdefine3(Integer idefine3) {
        this.idefine3 = idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE4
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.IDEFINE4
     *
     * @mbggenerated
     */
    public Integer getIdefine4() {
        return idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE4
     *
     * @param idefine4 the value for FCT_EXZONEDETAILSTATUS.IDEFINE4
     *
     * @mbggenerated
     */
    public void setIdefine4(Integer idefine4) {
        this.idefine4 = idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE5
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.IDEFINE5
     *
     * @mbggenerated
     */
    public Integer getIdefine5() {
        return idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.IDEFINE5
     *
     * @param idefine5 the value for FCT_EXZONEDETAILSTATUS.IDEFINE5
     *
     * @mbggenerated
     */
    public void setIdefine5(Integer idefine5) {
        this.idefine5 = idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE1
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.FDEFINE1
     *
     * @mbggenerated
     */
    public Double getFdefine1() {
        return fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE1
     *
     * @param fdefine1 the value for FCT_EXZONEDETAILSTATUS.FDEFINE1
     *
     * @mbggenerated
     */
    public void setFdefine1(Double fdefine1) {
        this.fdefine1 = fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE2
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.FDEFINE2
     *
     * @mbggenerated
     */
    public Double getFdefine2() {
        return fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE2
     *
     * @param fdefine2 the value for FCT_EXZONEDETAILSTATUS.FDEFINE2
     *
     * @mbggenerated
     */
    public void setFdefine2(Double fdefine2) {
        this.fdefine2 = fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE3
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.FDEFINE3
     *
     * @mbggenerated
     */
    public Double getFdefine3() {
        return fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE3
     *
     * @param fdefine3 the value for FCT_EXZONEDETAILSTATUS.FDEFINE3
     *
     * @mbggenerated
     */
    public void setFdefine3(Double fdefine3) {
        this.fdefine3 = fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE4
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.FDEFINE4
     *
     * @mbggenerated
     */
    public Double getFdefine4() {
        return fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE4
     *
     * @param fdefine4 the value for FCT_EXZONEDETAILSTATUS.FDEFINE4
     *
     * @mbggenerated
     */
    public void setFdefine4(Double fdefine4) {
        this.fdefine4 = fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE5
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.FDEFINE5
     *
     * @mbggenerated
     */
    public Double getFdefine5() {
        return fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.FDEFINE5
     *
     * @param fdefine5 the value for FCT_EXZONEDETAILSTATUS.FDEFINE5
     *
     * @mbggenerated
     */
    public void setFdefine5(Double fdefine5) {
        this.fdefine5 = fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE1
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SDEFINE1
     *
     * @mbggenerated
     */
    public String getSdefine1() {
        return sdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE1
     *
     * @param sdefine1 the value for FCT_EXZONEDETAILSTATUS.SDEFINE1
     *
     * @mbggenerated
     */
    public void setSdefine1(String sdefine1) {
        this.sdefine1 = sdefine1 == null ? null : sdefine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE2
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SDEFINE2
     *
     * @mbggenerated
     */
    public String getSdefine2() {
        return sdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE2
     *
     * @param sdefine2 the value for FCT_EXZONEDETAILSTATUS.SDEFINE2
     *
     * @mbggenerated
     */
    public void setSdefine2(String sdefine2) {
        this.sdefine2 = sdefine2 == null ? null : sdefine2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE3
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SDEFINE3
     *
     * @mbggenerated
     */
    public String getSdefine3() {
        return sdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE3
     *
     * @param sdefine3 the value for FCT_EXZONEDETAILSTATUS.SDEFINE3
     *
     * @mbggenerated
     */
    public void setSdefine3(String sdefine3) {
        this.sdefine3 = sdefine3 == null ? null : sdefine3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE4
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SDEFINE4
     *
     * @mbggenerated
     */
    public String getSdefine4() {
        return sdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE4
     *
     * @param sdefine4 the value for FCT_EXZONEDETAILSTATUS.SDEFINE4
     *
     * @mbggenerated
     */
    public void setSdefine4(String sdefine4) {
        this.sdefine4 = sdefine4 == null ? null : sdefine4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE5
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.SDEFINE5
     *
     * @mbggenerated
     */
    public String getSdefine5() {
        return sdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.SDEFINE5
     *
     * @param sdefine5 the value for FCT_EXZONEDETAILSTATUS.SDEFINE5
     *
     * @mbggenerated
     */
    public void setSdefine5(String sdefine5) {
        this.sdefine5 = sdefine5 == null ? null : sdefine5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.ATTACH
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.ATTACH
     *
     * @mbggenerated
     */
    public Long getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.ATTACH
     *
     * @param attach the value for FCT_EXZONEDETAILSTATUS.ATTACH
     *
     * @mbggenerated
     */
    public void setAttach(Long attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.PART
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.PART
     *
     * @mbggenerated
     */
    public Long getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.PART
     *
     * @param part the value for FCT_EXZONEDETAILSTATUS.PART
     *
     * @mbggenerated
     */
    public void setPart(Long part) {
        this.part = part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.MO
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.MO
     *
     * @mbggenerated
     */
    public Long getMo() {
        return mo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.MO
     *
     * @param mo the value for FCT_EXZONEDETAILSTATUS.MO
     *
     * @mbggenerated
     */
    public void setMo(Long mo) {
        this.mo = mo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.WORKGUIDEDETAIL
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.WORKGUIDEDETAIL
     *
     * @mbggenerated
     */
    public Long getWorkguidedetail() {
        return workguidedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.WORKGUIDEDETAIL
     *
     * @param workguidedetail the value for FCT_EXZONEDETAILSTATUS.WORKGUIDEDETAIL
     *
     * @mbggenerated
     */
    public void setWorkguidedetail(Long workguidedetail) {
        this.workguidedetail = workguidedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.EXZONE
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.EXZONE
     *
     * @mbggenerated
     */
    public Long getExzone() {
        return exzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.EXZONE
     *
     * @param exzone the value for FCT_EXZONEDETAILSTATUS.EXZONE
     *
     * @mbggenerated
     */
    public void setExzone(Long exzone) {
        this.exzone = exzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORCOMPLETED
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.QTYFORCOMPLETED
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforcompleted() {
        return qtyforcompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORCOMPLETED
     *
     * @param qtyforcompleted the value for FCT_EXZONEDETAILSTATUS.QTYFORCOMPLETED
     *
     * @mbggenerated
     */
    public void setQtyforcompleted(BigDecimal qtyforcompleted) {
        this.qtyforcompleted = qtyforcompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORRECEIVED
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.QTYFORRECEIVED
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforreceived() {
        return qtyforreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORRECEIVED
     *
     * @param qtyforreceived the value for FCT_EXZONEDETAILSTATUS.QTYFORRECEIVED
     *
     * @mbggenerated
     */
    public void setQtyforreceived(BigDecimal qtyforreceived) {
        this.qtyforreceived = qtyforreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORMERGE
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.QTYFORMERGE
     *
     * @mbggenerated
     */
    public BigDecimal getQtyformerge() {
        return qtyformerge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORMERGE
     *
     * @param qtyformerge the value for FCT_EXZONEDETAILSTATUS.QTYFORMERGE
     *
     * @mbggenerated
     */
    public void setQtyformerge(BigDecimal qtyformerge) {
        this.qtyformerge = qtyformerge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORPROCESSING
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.QTYFORPROCESSING
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforprocessing() {
        return qtyforprocessing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORPROCESSING
     *
     * @param qtyforprocessing the value for FCT_EXZONEDETAILSTATUS.QTYFORPROCESSING
     *
     * @mbggenerated
     */
    public void setQtyforprocessing(BigDecimal qtyforprocessing) {
        this.qtyforprocessing = qtyforprocessing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORSKIP
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.QTYFORSKIP
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforskip() {
        return qtyforskip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORSKIP
     *
     * @param qtyforskip the value for FCT_EXZONEDETAILSTATUS.QTYFORSKIP
     *
     * @mbggenerated
     */
    public void setQtyforskip(BigDecimal qtyforskip) {
        this.qtyforskip = qtyforskip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORREWORK
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.QTYFORREWORK
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforrework() {
        return qtyforrework;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORREWORK
     *
     * @param qtyforrework the value for FCT_EXZONEDETAILSTATUS.QTYFORREWORK
     *
     * @mbggenerated
     */
    public void setQtyforrework(BigDecimal qtyforrework) {
        this.qtyforrework = qtyforrework;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.UNIT
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.UNIT
     *
     * @param unit the value for FCT_EXZONEDETAILSTATUS.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.TRACECODE
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.TRACECODE
     *
     * @mbggenerated
     */
    public String getTracecode() {
        return tracecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.TRACECODE
     *
     * @param tracecode the value for FCT_EXZONEDETAILSTATUS.TRACECODE
     *
     * @mbggenerated
     */
    public void setTracecode(String tracecode) {
        this.tracecode = tracecode == null ? null : tracecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.STAGE
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.STAGE
     *
     * @mbggenerated
     */
    public Long getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.STAGE
     *
     * @param stage the value for FCT_EXZONEDETAILSTATUS.STAGE
     *
     * @mbggenerated
     */
    public void setStage(Long stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORSUPER
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.QTYFORSUPER
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforsuper() {
        return qtyforsuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORSUPER
     *
     * @param qtyforsuper the value for FCT_EXZONEDETAILSTATUS.QTYFORSUPER
     *
     * @mbggenerated
     */
    public void setQtyforsuper(BigDecimal qtyforsuper) {
        this.qtyforsuper = qtyforsuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORSCRAP
     *
     * @return the value of FCT_EXZONEDETAILSTATUS.QTYFORSCRAP
     *
     * @mbggenerated
     */
    public BigDecimal getQtyforscrap() {
        return qtyforscrap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_EXZONEDETAILSTATUS.QTYFORSCRAP
     *
     * @param qtyforscrap the value for FCT_EXZONEDETAILSTATUS.QTYFORSCRAP
     *
     * @mbggenerated
     */
    public void setQtyforscrap(BigDecimal qtyforscrap) {
        this.qtyforscrap = qtyforscrap;
    }
}