package com.debug.mybatis.entity;

import java.math.BigDecimal;

public class FctWorkguidedetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.AUTOID
     *
     * @mbggenerated
     */
    private Long autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SYS_ORG
     *
     * @mbggenerated
     */
    private Long sysOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    private String sysCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    private String sysModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SYS_CREATOR
     *
     * @mbggenerated
     */
    private String sysCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SYS_MODIFIER
     *
     * @mbggenerated
     */
    private String sysModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.FLAG
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.IDEFINE1
     *
     * @mbggenerated
     */
    private Integer idefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.IDEFINE2
     *
     * @mbggenerated
     */
    private Integer idefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.IDEFINE3
     *
     * @mbggenerated
     */
    private Integer idefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.IDEFINE4
     *
     * @mbggenerated
     */
    private Integer idefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.IDEFINE5
     *
     * @mbggenerated
     */
    private Integer idefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.FDEFINE1
     *
     * @mbggenerated
     */
    private Double fdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.FDEFINE2
     *
     * @mbggenerated
     */
    private Double fdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.FDEFINE3
     *
     * @mbggenerated
     */
    private Double fdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.FDEFINE4
     *
     * @mbggenerated
     */
    private Double fdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.FDEFINE5
     *
     * @mbggenerated
     */
    private Double fdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SDEFINE1
     *
     * @mbggenerated
     */
    private String sdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SDEFINE2
     *
     * @mbggenerated
     */
    private String sdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SDEFINE3
     *
     * @mbggenerated
     */
    private String sdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SDEFINE4
     *
     * @mbggenerated
     */
    private String sdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SDEFINE5
     *
     * @mbggenerated
     */
    private String sdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.ATTACH
     *
     * @mbggenerated
     */
    private Long attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.LINE
     *
     * @mbggenerated
     */
    private Integer line;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.WORKGUIDE
     *
     * @mbggenerated
     */
    private Long workguide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.ROUTING
     *
     * @mbggenerated
     */
    private Long routing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.STAGE
     *
     * @mbggenerated
     */
    private Long stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.STAGENAME
     *
     * @mbggenerated
     */
    private String stagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.FROMEXZONE
     *
     * @mbggenerated
     */
    private Long fromexzone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.TOEXZONE
     *
     * @mbggenerated
     */
    private Long toexzone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.OPERATION
     *
     * @mbggenerated
     */
    private Long operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.OPENDATE
     *
     * @mbggenerated
     */
    private String opendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.DUEDATE
     *
     * @mbggenerated
     */
    private String duedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.DEPARTMENT
     *
     * @mbggenerated
     */
    private Long department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.ROUTINGCODE
     *
     * @mbggenerated
     */
    private String routingcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.ROUTINGDESC
     *
     * @mbggenerated
     */
    private String routingdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.REWORKGUIDEDETAIL
     *
     * @mbggenerated
     */
    private Long reworkguidedetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.APPEND
     *
     * @mbggenerated
     */
    private Boolean append;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.TERM
     *
     * @mbggenerated
     */
    private Boolean term;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.RATE
     *
     * @mbggenerated
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.AUXILIARYUNIT
     *
     * @mbggenerated
     */
    private String auxiliaryunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.UNITFORDECLARATION
     *
     * @mbggenerated
     */
    private String unitfordeclaration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.QUEUE
     *
     * @mbggenerated
     */
    private Integer queue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.BASERATE
     *
     * @mbggenerated
     */
    private BigDecimal baserate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.AUXILIARYACCURACY
     *
     * @mbggenerated
     */
    private Integer auxiliaryaccuracy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.GROUPABLE
     *
     * @mbggenerated
     */
    private Boolean groupable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.GROUPID
     *
     * @mbggenerated
     */
    private Long groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.OVERTIME
     *
     * @mbggenerated
     */
    private String overtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.PERIOD
     *
     * @mbggenerated
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.PERIODTYPE
     *
     * @mbggenerated
     */
    private Integer periodtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.BASEPERIOD
     *
     * @mbggenerated
     */
    private Integer baseperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.PRICE
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SDEFINE7
     *
     * @mbggenerated
     */
    private String sdefine7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.SALESPRIORITY
     *
     * @mbggenerated
     */
    private Integer salespriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.TRANSFERBATCH
     *
     * @mbggenerated
     */
    private BigDecimal transferbatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.COMPLATEQTY
     *
     * @mbggenerated
     */
    private BigDecimal complateqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.UNTREATEDQTY
     *
     * @mbggenerated
     */
    private BigDecimal untreatedqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.WAITINGTIME
     *
     * @mbggenerated
     */
    private BigDecimal waitingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDEDETAIL.PARALLELSWITCH
     *
     * @mbggenerated
     */
    private Boolean parallelswitch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.AUTOID
     *
     * @return the value of FCT_WORKGUIDEDETAIL.AUTOID
     *
     * @mbggenerated
     */
    public Long getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.AUTOID
     *
     * @param autoid the value for FCT_WORKGUIDEDETAIL.AUTOID
     *
     * @mbggenerated
     */
    public void setAutoid(Long autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SYS_ORG
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SYS_ORG
     *
     * @mbggenerated
     */
    public Long getSysOrg() {
        return sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SYS_ORG
     *
     * @param sysOrg the value for FCT_WORKGUIDEDETAIL.SYS_ORG
     *
     * @mbggenerated
     */
    public void setSysOrg(Long sysOrg) {
        this.sysOrg = sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SYS_CREATE_DATE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public String getSysCreateDate() {
        return sysCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SYS_CREATE_DATE
     *
     * @param sysCreateDate the value for FCT_WORKGUIDEDETAIL.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setSysCreateDate(String sysCreateDate) {
        this.sysCreateDate = sysCreateDate == null ? null : sysCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SYS_MODIFY_DATE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public String getSysModifyDate() {
        return sysModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SYS_MODIFY_DATE
     *
     * @param sysModifyDate the value for FCT_WORKGUIDEDETAIL.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setSysModifyDate(String sysModifyDate) {
        this.sysModifyDate = sysModifyDate == null ? null : sysModifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SYS_CREATOR
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SYS_CREATOR
     *
     * @mbggenerated
     */
    public String getSysCreator() {
        return sysCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SYS_CREATOR
     *
     * @param sysCreator the value for FCT_WORKGUIDEDETAIL.SYS_CREATOR
     *
     * @mbggenerated
     */
    public void setSysCreator(String sysCreator) {
        this.sysCreator = sysCreator == null ? null : sysCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SYS_MODIFIER
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public String getSysModifier() {
        return sysModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SYS_MODIFIER
     *
     * @param sysModifier the value for FCT_WORKGUIDEDETAIL.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public void setSysModifier(String sysModifier) {
        this.sysModifier = sysModifier == null ? null : sysModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.FLAG
     *
     * @return the value of FCT_WORKGUIDEDETAIL.FLAG
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.FLAG
     *
     * @param flag the value for FCT_WORKGUIDEDETAIL.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE1
     *
     * @return the value of FCT_WORKGUIDEDETAIL.IDEFINE1
     *
     * @mbggenerated
     */
    public Integer getIdefine1() {
        return idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE1
     *
     * @param idefine1 the value for FCT_WORKGUIDEDETAIL.IDEFINE1
     *
     * @mbggenerated
     */
    public void setIdefine1(Integer idefine1) {
        this.idefine1 = idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE2
     *
     * @return the value of FCT_WORKGUIDEDETAIL.IDEFINE2
     *
     * @mbggenerated
     */
    public Integer getIdefine2() {
        return idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE2
     *
     * @param idefine2 the value for FCT_WORKGUIDEDETAIL.IDEFINE2
     *
     * @mbggenerated
     */
    public void setIdefine2(Integer idefine2) {
        this.idefine2 = idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE3
     *
     * @return the value of FCT_WORKGUIDEDETAIL.IDEFINE3
     *
     * @mbggenerated
     */
    public Integer getIdefine3() {
        return idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE3
     *
     * @param idefine3 the value for FCT_WORKGUIDEDETAIL.IDEFINE3
     *
     * @mbggenerated
     */
    public void setIdefine3(Integer idefine3) {
        this.idefine3 = idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE4
     *
     * @return the value of FCT_WORKGUIDEDETAIL.IDEFINE4
     *
     * @mbggenerated
     */
    public Integer getIdefine4() {
        return idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE4
     *
     * @param idefine4 the value for FCT_WORKGUIDEDETAIL.IDEFINE4
     *
     * @mbggenerated
     */
    public void setIdefine4(Integer idefine4) {
        this.idefine4 = idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE5
     *
     * @return the value of FCT_WORKGUIDEDETAIL.IDEFINE5
     *
     * @mbggenerated
     */
    public Integer getIdefine5() {
        return idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.IDEFINE5
     *
     * @param idefine5 the value for FCT_WORKGUIDEDETAIL.IDEFINE5
     *
     * @mbggenerated
     */
    public void setIdefine5(Integer idefine5) {
        this.idefine5 = idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE1
     *
     * @return the value of FCT_WORKGUIDEDETAIL.FDEFINE1
     *
     * @mbggenerated
     */
    public Double getFdefine1() {
        return fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE1
     *
     * @param fdefine1 the value for FCT_WORKGUIDEDETAIL.FDEFINE1
     *
     * @mbggenerated
     */
    public void setFdefine1(Double fdefine1) {
        this.fdefine1 = fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE2
     *
     * @return the value of FCT_WORKGUIDEDETAIL.FDEFINE2
     *
     * @mbggenerated
     */
    public Double getFdefine2() {
        return fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE2
     *
     * @param fdefine2 the value for FCT_WORKGUIDEDETAIL.FDEFINE2
     *
     * @mbggenerated
     */
    public void setFdefine2(Double fdefine2) {
        this.fdefine2 = fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE3
     *
     * @return the value of FCT_WORKGUIDEDETAIL.FDEFINE3
     *
     * @mbggenerated
     */
    public Double getFdefine3() {
        return fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE3
     *
     * @param fdefine3 the value for FCT_WORKGUIDEDETAIL.FDEFINE3
     *
     * @mbggenerated
     */
    public void setFdefine3(Double fdefine3) {
        this.fdefine3 = fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE4
     *
     * @return the value of FCT_WORKGUIDEDETAIL.FDEFINE4
     *
     * @mbggenerated
     */
    public Double getFdefine4() {
        return fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE4
     *
     * @param fdefine4 the value for FCT_WORKGUIDEDETAIL.FDEFINE4
     *
     * @mbggenerated
     */
    public void setFdefine4(Double fdefine4) {
        this.fdefine4 = fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE5
     *
     * @return the value of FCT_WORKGUIDEDETAIL.FDEFINE5
     *
     * @mbggenerated
     */
    public Double getFdefine5() {
        return fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.FDEFINE5
     *
     * @param fdefine5 the value for FCT_WORKGUIDEDETAIL.FDEFINE5
     *
     * @mbggenerated
     */
    public void setFdefine5(Double fdefine5) {
        this.fdefine5 = fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE1
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SDEFINE1
     *
     * @mbggenerated
     */
    public String getSdefine1() {
        return sdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE1
     *
     * @param sdefine1 the value for FCT_WORKGUIDEDETAIL.SDEFINE1
     *
     * @mbggenerated
     */
    public void setSdefine1(String sdefine1) {
        this.sdefine1 = sdefine1 == null ? null : sdefine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE2
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SDEFINE2
     *
     * @mbggenerated
     */
    public String getSdefine2() {
        return sdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE2
     *
     * @param sdefine2 the value for FCT_WORKGUIDEDETAIL.SDEFINE2
     *
     * @mbggenerated
     */
    public void setSdefine2(String sdefine2) {
        this.sdefine2 = sdefine2 == null ? null : sdefine2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE3
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SDEFINE3
     *
     * @mbggenerated
     */
    public String getSdefine3() {
        return sdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE3
     *
     * @param sdefine3 the value for FCT_WORKGUIDEDETAIL.SDEFINE3
     *
     * @mbggenerated
     */
    public void setSdefine3(String sdefine3) {
        this.sdefine3 = sdefine3 == null ? null : sdefine3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE4
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SDEFINE4
     *
     * @mbggenerated
     */
    public String getSdefine4() {
        return sdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE4
     *
     * @param sdefine4 the value for FCT_WORKGUIDEDETAIL.SDEFINE4
     *
     * @mbggenerated
     */
    public void setSdefine4(String sdefine4) {
        this.sdefine4 = sdefine4 == null ? null : sdefine4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE5
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SDEFINE5
     *
     * @mbggenerated
     */
    public String getSdefine5() {
        return sdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE5
     *
     * @param sdefine5 the value for FCT_WORKGUIDEDETAIL.SDEFINE5
     *
     * @mbggenerated
     */
    public void setSdefine5(String sdefine5) {
        this.sdefine5 = sdefine5 == null ? null : sdefine5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.ATTACH
     *
     * @return the value of FCT_WORKGUIDEDETAIL.ATTACH
     *
     * @mbggenerated
     */
    public Long getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.ATTACH
     *
     * @param attach the value for FCT_WORKGUIDEDETAIL.ATTACH
     *
     * @mbggenerated
     */
    public void setAttach(Long attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.LINE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.LINE
     *
     * @mbggenerated
     */
    public Integer getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.LINE
     *
     * @param line the value for FCT_WORKGUIDEDETAIL.LINE
     *
     * @mbggenerated
     */
    public void setLine(Integer line) {
        this.line = line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.WORKGUIDE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.WORKGUIDE
     *
     * @mbggenerated
     */
    public Long getWorkguide() {
        return workguide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.WORKGUIDE
     *
     * @param workguide the value for FCT_WORKGUIDEDETAIL.WORKGUIDE
     *
     * @mbggenerated
     */
    public void setWorkguide(Long workguide) {
        this.workguide = workguide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.ROUTING
     *
     * @return the value of FCT_WORKGUIDEDETAIL.ROUTING
     *
     * @mbggenerated
     */
    public Long getRouting() {
        return routing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.ROUTING
     *
     * @param routing the value for FCT_WORKGUIDEDETAIL.ROUTING
     *
     * @mbggenerated
     */
    public void setRouting(Long routing) {
        this.routing = routing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.STAGE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.STAGE
     *
     * @mbggenerated
     */
    public Long getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.STAGE
     *
     * @param stage the value for FCT_WORKGUIDEDETAIL.STAGE
     *
     * @mbggenerated
     */
    public void setStage(Long stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.STAGENAME
     *
     * @return the value of FCT_WORKGUIDEDETAIL.STAGENAME
     *
     * @mbggenerated
     */
    public String getStagename() {
        return stagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.STAGENAME
     *
     * @param stagename the value for FCT_WORKGUIDEDETAIL.STAGENAME
     *
     * @mbggenerated
     */
    public void setStagename(String stagename) {
        this.stagename = stagename == null ? null : stagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.FROMEXZONE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.FROMEXZONE
     *
     * @mbggenerated
     */
    public Long getFromexzone() {
        return fromexzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.FROMEXZONE
     *
     * @param fromexzone the value for FCT_WORKGUIDEDETAIL.FROMEXZONE
     *
     * @mbggenerated
     */
    public void setFromexzone(Long fromexzone) {
        this.fromexzone = fromexzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.TOEXZONE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.TOEXZONE
     *
     * @mbggenerated
     */
    public Long getToexzone() {
        return toexzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.TOEXZONE
     *
     * @param toexzone the value for FCT_WORKGUIDEDETAIL.TOEXZONE
     *
     * @mbggenerated
     */
    public void setToexzone(Long toexzone) {
        this.toexzone = toexzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.OPERATION
     *
     * @return the value of FCT_WORKGUIDEDETAIL.OPERATION
     *
     * @mbggenerated
     */
    public Long getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.OPERATION
     *
     * @param operation the value for FCT_WORKGUIDEDETAIL.OPERATION
     *
     * @mbggenerated
     */
    public void setOperation(Long operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.OPENDATE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.OPENDATE
     *
     * @mbggenerated
     */
    public String getOpendate() {
        return opendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.OPENDATE
     *
     * @param opendate the value for FCT_WORKGUIDEDETAIL.OPENDATE
     *
     * @mbggenerated
     */
    public void setOpendate(String opendate) {
        this.opendate = opendate == null ? null : opendate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.DUEDATE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.DUEDATE
     *
     * @mbggenerated
     */
    public String getDuedate() {
        return duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.DUEDATE
     *
     * @param duedate the value for FCT_WORKGUIDEDETAIL.DUEDATE
     *
     * @mbggenerated
     */
    public void setDuedate(String duedate) {
        this.duedate = duedate == null ? null : duedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.DEPARTMENT
     *
     * @return the value of FCT_WORKGUIDEDETAIL.DEPARTMENT
     *
     * @mbggenerated
     */
    public Long getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.DEPARTMENT
     *
     * @param department the value for FCT_WORKGUIDEDETAIL.DEPARTMENT
     *
     * @mbggenerated
     */
    public void setDepartment(Long department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.ROUTINGCODE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.ROUTINGCODE
     *
     * @mbggenerated
     */
    public String getRoutingcode() {
        return routingcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.ROUTINGCODE
     *
     * @param routingcode the value for FCT_WORKGUIDEDETAIL.ROUTINGCODE
     *
     * @mbggenerated
     */
    public void setRoutingcode(String routingcode) {
        this.routingcode = routingcode == null ? null : routingcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.ROUTINGDESC
     *
     * @return the value of FCT_WORKGUIDEDETAIL.ROUTINGDESC
     *
     * @mbggenerated
     */
    public String getRoutingdesc() {
        return routingdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.ROUTINGDESC
     *
     * @param routingdesc the value for FCT_WORKGUIDEDETAIL.ROUTINGDESC
     *
     * @mbggenerated
     */
    public void setRoutingdesc(String routingdesc) {
        this.routingdesc = routingdesc == null ? null : routingdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.REWORKGUIDEDETAIL
     *
     * @return the value of FCT_WORKGUIDEDETAIL.REWORKGUIDEDETAIL
     *
     * @mbggenerated
     */
    public Long getReworkguidedetail() {
        return reworkguidedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.REWORKGUIDEDETAIL
     *
     * @param reworkguidedetail the value for FCT_WORKGUIDEDETAIL.REWORKGUIDEDETAIL
     *
     * @mbggenerated
     */
    public void setReworkguidedetail(Long reworkguidedetail) {
        this.reworkguidedetail = reworkguidedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.APPEND
     *
     * @return the value of FCT_WORKGUIDEDETAIL.APPEND
     *
     * @mbggenerated
     */
    public Boolean getAppend() {
        return append;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.APPEND
     *
     * @param append the value for FCT_WORKGUIDEDETAIL.APPEND
     *
     * @mbggenerated
     */
    public void setAppend(Boolean append) {
        this.append = append;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.TERM
     *
     * @return the value of FCT_WORKGUIDEDETAIL.TERM
     *
     * @mbggenerated
     */
    public Boolean getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.TERM
     *
     * @param term the value for FCT_WORKGUIDEDETAIL.TERM
     *
     * @mbggenerated
     */
    public void setTerm(Boolean term) {
        this.term = term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.RATE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.RATE
     *
     * @mbggenerated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.RATE
     *
     * @param rate the value for FCT_WORKGUIDEDETAIL.RATE
     *
     * @mbggenerated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.AUXILIARYUNIT
     *
     * @return the value of FCT_WORKGUIDEDETAIL.AUXILIARYUNIT
     *
     * @mbggenerated
     */
    public String getAuxiliaryunit() {
        return auxiliaryunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.AUXILIARYUNIT
     *
     * @param auxiliaryunit the value for FCT_WORKGUIDEDETAIL.AUXILIARYUNIT
     *
     * @mbggenerated
     */
    public void setAuxiliaryunit(String auxiliaryunit) {
        this.auxiliaryunit = auxiliaryunit == null ? null : auxiliaryunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.UNITFORDECLARATION
     *
     * @return the value of FCT_WORKGUIDEDETAIL.UNITFORDECLARATION
     *
     * @mbggenerated
     */
    public String getUnitfordeclaration() {
        return unitfordeclaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.UNITFORDECLARATION
     *
     * @param unitfordeclaration the value for FCT_WORKGUIDEDETAIL.UNITFORDECLARATION
     *
     * @mbggenerated
     */
    public void setUnitfordeclaration(String unitfordeclaration) {
        this.unitfordeclaration = unitfordeclaration == null ? null : unitfordeclaration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.QUEUE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.QUEUE
     *
     * @mbggenerated
     */
    public Integer getQueue() {
        return queue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.QUEUE
     *
     * @param queue the value for FCT_WORKGUIDEDETAIL.QUEUE
     *
     * @mbggenerated
     */
    public void setQueue(Integer queue) {
        this.queue = queue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.BASERATE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.BASERATE
     *
     * @mbggenerated
     */
    public BigDecimal getBaserate() {
        return baserate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.BASERATE
     *
     * @param baserate the value for FCT_WORKGUIDEDETAIL.BASERATE
     *
     * @mbggenerated
     */
    public void setBaserate(BigDecimal baserate) {
        this.baserate = baserate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.AUXILIARYACCURACY
     *
     * @return the value of FCT_WORKGUIDEDETAIL.AUXILIARYACCURACY
     *
     * @mbggenerated
     */
    public Integer getAuxiliaryaccuracy() {
        return auxiliaryaccuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.AUXILIARYACCURACY
     *
     * @param auxiliaryaccuracy the value for FCT_WORKGUIDEDETAIL.AUXILIARYACCURACY
     *
     * @mbggenerated
     */
    public void setAuxiliaryaccuracy(Integer auxiliaryaccuracy) {
        this.auxiliaryaccuracy = auxiliaryaccuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.GROUPABLE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.GROUPABLE
     *
     * @mbggenerated
     */
    public Boolean getGroupable() {
        return groupable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.GROUPABLE
     *
     * @param groupable the value for FCT_WORKGUIDEDETAIL.GROUPABLE
     *
     * @mbggenerated
     */
    public void setGroupable(Boolean groupable) {
        this.groupable = groupable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.GROUPID
     *
     * @return the value of FCT_WORKGUIDEDETAIL.GROUPID
     *
     * @mbggenerated
     */
    public Long getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.GROUPID
     *
     * @param groupid the value for FCT_WORKGUIDEDETAIL.GROUPID
     *
     * @mbggenerated
     */
    public void setGroupid(Long groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.OVERTIME
     *
     * @return the value of FCT_WORKGUIDEDETAIL.OVERTIME
     *
     * @mbggenerated
     */
    public String getOvertime() {
        return overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.OVERTIME
     *
     * @param overtime the value for FCT_WORKGUIDEDETAIL.OVERTIME
     *
     * @mbggenerated
     */
    public void setOvertime(String overtime) {
        this.overtime = overtime == null ? null : overtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.PERIOD
     *
     * @return the value of FCT_WORKGUIDEDETAIL.PERIOD
     *
     * @mbggenerated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.PERIOD
     *
     * @param period the value for FCT_WORKGUIDEDETAIL.PERIOD
     *
     * @mbggenerated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.PERIODTYPE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.PERIODTYPE
     *
     * @mbggenerated
     */
    public Integer getPeriodtype() {
        return periodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.PERIODTYPE
     *
     * @param periodtype the value for FCT_WORKGUIDEDETAIL.PERIODTYPE
     *
     * @mbggenerated
     */
    public void setPeriodtype(Integer periodtype) {
        this.periodtype = periodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.BASEPERIOD
     *
     * @return the value of FCT_WORKGUIDEDETAIL.BASEPERIOD
     *
     * @mbggenerated
     */
    public Integer getBaseperiod() {
        return baseperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.BASEPERIOD
     *
     * @param baseperiod the value for FCT_WORKGUIDEDETAIL.BASEPERIOD
     *
     * @mbggenerated
     */
    public void setBaseperiod(Integer baseperiod) {
        this.baseperiod = baseperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.PRICE
     *
     * @return the value of FCT_WORKGUIDEDETAIL.PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.PRICE
     *
     * @param price the value for FCT_WORKGUIDEDETAIL.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.REMARK
     *
     * @return the value of FCT_WORKGUIDEDETAIL.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.REMARK
     *
     * @param remark the value for FCT_WORKGUIDEDETAIL.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE7
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SDEFINE7
     *
     * @mbggenerated
     */
    public String getSdefine7() {
        return sdefine7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SDEFINE7
     *
     * @param sdefine7 the value for FCT_WORKGUIDEDETAIL.SDEFINE7
     *
     * @mbggenerated
     */
    public void setSdefine7(String sdefine7) {
        this.sdefine7 = sdefine7 == null ? null : sdefine7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.SALESPRIORITY
     *
     * @return the value of FCT_WORKGUIDEDETAIL.SALESPRIORITY
     *
     * @mbggenerated
     */
    public Integer getSalespriority() {
        return salespriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.SALESPRIORITY
     *
     * @param salespriority the value for FCT_WORKGUIDEDETAIL.SALESPRIORITY
     *
     * @mbggenerated
     */
    public void setSalespriority(Integer salespriority) {
        this.salespriority = salespriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.TRANSFERBATCH
     *
     * @return the value of FCT_WORKGUIDEDETAIL.TRANSFERBATCH
     *
     * @mbggenerated
     */
    public BigDecimal getTransferbatch() {
        return transferbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.TRANSFERBATCH
     *
     * @param transferbatch the value for FCT_WORKGUIDEDETAIL.TRANSFERBATCH
     *
     * @mbggenerated
     */
    public void setTransferbatch(BigDecimal transferbatch) {
        this.transferbatch = transferbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.COMPLATEQTY
     *
     * @return the value of FCT_WORKGUIDEDETAIL.COMPLATEQTY
     *
     * @mbggenerated
     */
    public BigDecimal getComplateqty() {
        return complateqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.COMPLATEQTY
     *
     * @param complateqty the value for FCT_WORKGUIDEDETAIL.COMPLATEQTY
     *
     * @mbggenerated
     */
    public void setComplateqty(BigDecimal complateqty) {
        this.complateqty = complateqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.UNTREATEDQTY
     *
     * @return the value of FCT_WORKGUIDEDETAIL.UNTREATEDQTY
     *
     * @mbggenerated
     */
    public BigDecimal getUntreatedqty() {
        return untreatedqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.UNTREATEDQTY
     *
     * @param untreatedqty the value for FCT_WORKGUIDEDETAIL.UNTREATEDQTY
     *
     * @mbggenerated
     */
    public void setUntreatedqty(BigDecimal untreatedqty) {
        this.untreatedqty = untreatedqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.WAITINGTIME
     *
     * @return the value of FCT_WORKGUIDEDETAIL.WAITINGTIME
     *
     * @mbggenerated
     */
    public BigDecimal getWaitingtime() {
        return waitingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.WAITINGTIME
     *
     * @param waitingtime the value for FCT_WORKGUIDEDETAIL.WAITINGTIME
     *
     * @mbggenerated
     */
    public void setWaitingtime(BigDecimal waitingtime) {
        this.waitingtime = waitingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDEDETAIL.PARALLELSWITCH
     *
     * @return the value of FCT_WORKGUIDEDETAIL.PARALLELSWITCH
     *
     * @mbggenerated
     */
    public Boolean getParallelswitch() {
        return parallelswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDEDETAIL.PARALLELSWITCH
     *
     * @param parallelswitch the value for FCT_WORKGUIDEDETAIL.PARALLELSWITCH
     *
     * @mbggenerated
     */
    public void setParallelswitch(Boolean parallelswitch) {
        this.parallelswitch = parallelswitch;
    }
}