package com.debug.mybatis.entity;

import java.math.BigDecimal;

public class FctWorkguidestage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SYS_ORG
     *
     * @mbggenerated
     */
    private Long sysOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    private String sysCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    private String sysModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SYS_CREATOR
     *
     * @mbggenerated
     */
    private String sysCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SYS_MODIFIER
     *
     * @mbggenerated
     */
    private String sysModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.FLAG
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.AUTOID
     *
     * @mbggenerated
     */
    private Long autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.IDEFINE1
     *
     * @mbggenerated
     */
    private Integer idefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.IDEFINE2
     *
     * @mbggenerated
     */
    private Integer idefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.IDEFINE3
     *
     * @mbggenerated
     */
    private Integer idefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.IDEFINE4
     *
     * @mbggenerated
     */
    private Integer idefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.IDEFINE5
     *
     * @mbggenerated
     */
    private Integer idefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.FDEFINE1
     *
     * @mbggenerated
     */
    private Double fdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.FDEFINE2
     *
     * @mbggenerated
     */
    private Double fdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.FDEFINE3
     *
     * @mbggenerated
     */
    private Double fdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.FDEFINE4
     *
     * @mbggenerated
     */
    private Double fdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.FDEFINE5
     *
     * @mbggenerated
     */
    private Double fdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SDEFINE1
     *
     * @mbggenerated
     */
    private String sdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SDEFINE2
     *
     * @mbggenerated
     */
    private String sdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SDEFINE3
     *
     * @mbggenerated
     */
    private String sdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SDEFINE4
     *
     * @mbggenerated
     */
    private String sdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.SDEFINE5
     *
     * @mbggenerated
     */
    private String sdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.ATTACH
     *
     * @mbggenerated
     */
    private Long attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.WORKGUIDE
     *
     * @mbggenerated
     */
    private Long workguide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.STAGE
     *
     * @mbggenerated
     */
    private Long stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.LINE
     *
     * @mbggenerated
     */
    private Integer line;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.FROMEXZONE
     *
     * @mbggenerated
     */
    private Long fromexzone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.TOEXZONE
     *
     * @mbggenerated
     */
    private Long toexzone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.CYCLEMODE
     *
     * @mbggenerated
     */
    private Integer cyclemode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.PARALLELCONTROL
     *
     * @mbggenerated
     */
    private Boolean parallelcontrol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.QCCAUSEOFREWORKCONTROLLER
     *
     * @mbggenerated
     */
    private Boolean qccauseofreworkcontroller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.QCCAUSEOFSCRPCONTROLLER
     *
     * @mbggenerated
     */
    private Boolean qccauseofscrpcontroller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.QCCAUSEOFREJECTCONTROLLER
     *
     * @mbggenerated
     */
    private Boolean qccauseofrejectcontroller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.PERIOD
     *
     * @mbggenerated
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.BASEPERIOD
     *
     * @mbggenerated
     */
    private Integer baseperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.PERIODTYPE
     *
     * @mbggenerated
     */
    private Integer periodtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.TRANSFERBATCH
     *
     * @mbggenerated
     */
    private Integer transferbatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDESTAGE.WAITINGTIME
     *
     * @mbggenerated
     */
    private BigDecimal waitingtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SYS_ORG
     *
     * @return the value of FCT_WORKGUIDESTAGE.SYS_ORG
     *
     * @mbggenerated
     */
    public Long getSysOrg() {
        return sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SYS_ORG
     *
     * @param sysOrg the value for FCT_WORKGUIDESTAGE.SYS_ORG
     *
     * @mbggenerated
     */
    public void setSysOrg(Long sysOrg) {
        this.sysOrg = sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SYS_CREATE_DATE
     *
     * @return the value of FCT_WORKGUIDESTAGE.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public String getSysCreateDate() {
        return sysCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SYS_CREATE_DATE
     *
     * @param sysCreateDate the value for FCT_WORKGUIDESTAGE.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setSysCreateDate(String sysCreateDate) {
        this.sysCreateDate = sysCreateDate == null ? null : sysCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SYS_MODIFY_DATE
     *
     * @return the value of FCT_WORKGUIDESTAGE.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public String getSysModifyDate() {
        return sysModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SYS_MODIFY_DATE
     *
     * @param sysModifyDate the value for FCT_WORKGUIDESTAGE.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setSysModifyDate(String sysModifyDate) {
        this.sysModifyDate = sysModifyDate == null ? null : sysModifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SYS_CREATOR
     *
     * @return the value of FCT_WORKGUIDESTAGE.SYS_CREATOR
     *
     * @mbggenerated
     */
    public String getSysCreator() {
        return sysCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SYS_CREATOR
     *
     * @param sysCreator the value for FCT_WORKGUIDESTAGE.SYS_CREATOR
     *
     * @mbggenerated
     */
    public void setSysCreator(String sysCreator) {
        this.sysCreator = sysCreator == null ? null : sysCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SYS_MODIFIER
     *
     * @return the value of FCT_WORKGUIDESTAGE.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public String getSysModifier() {
        return sysModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SYS_MODIFIER
     *
     * @param sysModifier the value for FCT_WORKGUIDESTAGE.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public void setSysModifier(String sysModifier) {
        this.sysModifier = sysModifier == null ? null : sysModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.FLAG
     *
     * @return the value of FCT_WORKGUIDESTAGE.FLAG
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.FLAG
     *
     * @param flag the value for FCT_WORKGUIDESTAGE.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.AUTOID
     *
     * @return the value of FCT_WORKGUIDESTAGE.AUTOID
     *
     * @mbggenerated
     */
    public Long getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.AUTOID
     *
     * @param autoid the value for FCT_WORKGUIDESTAGE.AUTOID
     *
     * @mbggenerated
     */
    public void setAutoid(Long autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.IDEFINE1
     *
     * @return the value of FCT_WORKGUIDESTAGE.IDEFINE1
     *
     * @mbggenerated
     */
    public Integer getIdefine1() {
        return idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.IDEFINE1
     *
     * @param idefine1 the value for FCT_WORKGUIDESTAGE.IDEFINE1
     *
     * @mbggenerated
     */
    public void setIdefine1(Integer idefine1) {
        this.idefine1 = idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.IDEFINE2
     *
     * @return the value of FCT_WORKGUIDESTAGE.IDEFINE2
     *
     * @mbggenerated
     */
    public Integer getIdefine2() {
        return idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.IDEFINE2
     *
     * @param idefine2 the value for FCT_WORKGUIDESTAGE.IDEFINE2
     *
     * @mbggenerated
     */
    public void setIdefine2(Integer idefine2) {
        this.idefine2 = idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.IDEFINE3
     *
     * @return the value of FCT_WORKGUIDESTAGE.IDEFINE3
     *
     * @mbggenerated
     */
    public Integer getIdefine3() {
        return idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.IDEFINE3
     *
     * @param idefine3 the value for FCT_WORKGUIDESTAGE.IDEFINE3
     *
     * @mbggenerated
     */
    public void setIdefine3(Integer idefine3) {
        this.idefine3 = idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.IDEFINE4
     *
     * @return the value of FCT_WORKGUIDESTAGE.IDEFINE4
     *
     * @mbggenerated
     */
    public Integer getIdefine4() {
        return idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.IDEFINE4
     *
     * @param idefine4 the value for FCT_WORKGUIDESTAGE.IDEFINE4
     *
     * @mbggenerated
     */
    public void setIdefine4(Integer idefine4) {
        this.idefine4 = idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.IDEFINE5
     *
     * @return the value of FCT_WORKGUIDESTAGE.IDEFINE5
     *
     * @mbggenerated
     */
    public Integer getIdefine5() {
        return idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.IDEFINE5
     *
     * @param idefine5 the value for FCT_WORKGUIDESTAGE.IDEFINE5
     *
     * @mbggenerated
     */
    public void setIdefine5(Integer idefine5) {
        this.idefine5 = idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.FDEFINE1
     *
     * @return the value of FCT_WORKGUIDESTAGE.FDEFINE1
     *
     * @mbggenerated
     */
    public Double getFdefine1() {
        return fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.FDEFINE1
     *
     * @param fdefine1 the value for FCT_WORKGUIDESTAGE.FDEFINE1
     *
     * @mbggenerated
     */
    public void setFdefine1(Double fdefine1) {
        this.fdefine1 = fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.FDEFINE2
     *
     * @return the value of FCT_WORKGUIDESTAGE.FDEFINE2
     *
     * @mbggenerated
     */
    public Double getFdefine2() {
        return fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.FDEFINE2
     *
     * @param fdefine2 the value for FCT_WORKGUIDESTAGE.FDEFINE2
     *
     * @mbggenerated
     */
    public void setFdefine2(Double fdefine2) {
        this.fdefine2 = fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.FDEFINE3
     *
     * @return the value of FCT_WORKGUIDESTAGE.FDEFINE3
     *
     * @mbggenerated
     */
    public Double getFdefine3() {
        return fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.FDEFINE3
     *
     * @param fdefine3 the value for FCT_WORKGUIDESTAGE.FDEFINE3
     *
     * @mbggenerated
     */
    public void setFdefine3(Double fdefine3) {
        this.fdefine3 = fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.FDEFINE4
     *
     * @return the value of FCT_WORKGUIDESTAGE.FDEFINE4
     *
     * @mbggenerated
     */
    public Double getFdefine4() {
        return fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.FDEFINE4
     *
     * @param fdefine4 the value for FCT_WORKGUIDESTAGE.FDEFINE4
     *
     * @mbggenerated
     */
    public void setFdefine4(Double fdefine4) {
        this.fdefine4 = fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.FDEFINE5
     *
     * @return the value of FCT_WORKGUIDESTAGE.FDEFINE5
     *
     * @mbggenerated
     */
    public Double getFdefine5() {
        return fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.FDEFINE5
     *
     * @param fdefine5 the value for FCT_WORKGUIDESTAGE.FDEFINE5
     *
     * @mbggenerated
     */
    public void setFdefine5(Double fdefine5) {
        this.fdefine5 = fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SDEFINE1
     *
     * @return the value of FCT_WORKGUIDESTAGE.SDEFINE1
     *
     * @mbggenerated
     */
    public String getSdefine1() {
        return sdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SDEFINE1
     *
     * @param sdefine1 the value for FCT_WORKGUIDESTAGE.SDEFINE1
     *
     * @mbggenerated
     */
    public void setSdefine1(String sdefine1) {
        this.sdefine1 = sdefine1 == null ? null : sdefine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SDEFINE2
     *
     * @return the value of FCT_WORKGUIDESTAGE.SDEFINE2
     *
     * @mbggenerated
     */
    public String getSdefine2() {
        return sdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SDEFINE2
     *
     * @param sdefine2 the value for FCT_WORKGUIDESTAGE.SDEFINE2
     *
     * @mbggenerated
     */
    public void setSdefine2(String sdefine2) {
        this.sdefine2 = sdefine2 == null ? null : sdefine2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SDEFINE3
     *
     * @return the value of FCT_WORKGUIDESTAGE.SDEFINE3
     *
     * @mbggenerated
     */
    public String getSdefine3() {
        return sdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SDEFINE3
     *
     * @param sdefine3 the value for FCT_WORKGUIDESTAGE.SDEFINE3
     *
     * @mbggenerated
     */
    public void setSdefine3(String sdefine3) {
        this.sdefine3 = sdefine3 == null ? null : sdefine3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SDEFINE4
     *
     * @return the value of FCT_WORKGUIDESTAGE.SDEFINE4
     *
     * @mbggenerated
     */
    public String getSdefine4() {
        return sdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SDEFINE4
     *
     * @param sdefine4 the value for FCT_WORKGUIDESTAGE.SDEFINE4
     *
     * @mbggenerated
     */
    public void setSdefine4(String sdefine4) {
        this.sdefine4 = sdefine4 == null ? null : sdefine4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.SDEFINE5
     *
     * @return the value of FCT_WORKGUIDESTAGE.SDEFINE5
     *
     * @mbggenerated
     */
    public String getSdefine5() {
        return sdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.SDEFINE5
     *
     * @param sdefine5 the value for FCT_WORKGUIDESTAGE.SDEFINE5
     *
     * @mbggenerated
     */
    public void setSdefine5(String sdefine5) {
        this.sdefine5 = sdefine5 == null ? null : sdefine5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.ATTACH
     *
     * @return the value of FCT_WORKGUIDESTAGE.ATTACH
     *
     * @mbggenerated
     */
    public Long getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.ATTACH
     *
     * @param attach the value for FCT_WORKGUIDESTAGE.ATTACH
     *
     * @mbggenerated
     */
    public void setAttach(Long attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.WORKGUIDE
     *
     * @return the value of FCT_WORKGUIDESTAGE.WORKGUIDE
     *
     * @mbggenerated
     */
    public Long getWorkguide() {
        return workguide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.WORKGUIDE
     *
     * @param workguide the value for FCT_WORKGUIDESTAGE.WORKGUIDE
     *
     * @mbggenerated
     */
    public void setWorkguide(Long workguide) {
        this.workguide = workguide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.STAGE
     *
     * @return the value of FCT_WORKGUIDESTAGE.STAGE
     *
     * @mbggenerated
     */
    public Long getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.STAGE
     *
     * @param stage the value for FCT_WORKGUIDESTAGE.STAGE
     *
     * @mbggenerated
     */
    public void setStage(Long stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.LINE
     *
     * @return the value of FCT_WORKGUIDESTAGE.LINE
     *
     * @mbggenerated
     */
    public Integer getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.LINE
     *
     * @param line the value for FCT_WORKGUIDESTAGE.LINE
     *
     * @mbggenerated
     */
    public void setLine(Integer line) {
        this.line = line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.CODE
     *
     * @return the value of FCT_WORKGUIDESTAGE.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.CODE
     *
     * @param code the value for FCT_WORKGUIDESTAGE.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.NAME
     *
     * @return the value of FCT_WORKGUIDESTAGE.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.NAME
     *
     * @param name the value for FCT_WORKGUIDESTAGE.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.FROMEXZONE
     *
     * @return the value of FCT_WORKGUIDESTAGE.FROMEXZONE
     *
     * @mbggenerated
     */
    public Long getFromexzone() {
        return fromexzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.FROMEXZONE
     *
     * @param fromexzone the value for FCT_WORKGUIDESTAGE.FROMEXZONE
     *
     * @mbggenerated
     */
    public void setFromexzone(Long fromexzone) {
        this.fromexzone = fromexzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.TOEXZONE
     *
     * @return the value of FCT_WORKGUIDESTAGE.TOEXZONE
     *
     * @mbggenerated
     */
    public Long getToexzone() {
        return toexzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.TOEXZONE
     *
     * @param toexzone the value for FCT_WORKGUIDESTAGE.TOEXZONE
     *
     * @mbggenerated
     */
    public void setToexzone(Long toexzone) {
        this.toexzone = toexzone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.CYCLEMODE
     *
     * @return the value of FCT_WORKGUIDESTAGE.CYCLEMODE
     *
     * @mbggenerated
     */
    public Integer getCyclemode() {
        return cyclemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.CYCLEMODE
     *
     * @param cyclemode the value for FCT_WORKGUIDESTAGE.CYCLEMODE
     *
     * @mbggenerated
     */
    public void setCyclemode(Integer cyclemode) {
        this.cyclemode = cyclemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.PARALLELCONTROL
     *
     * @return the value of FCT_WORKGUIDESTAGE.PARALLELCONTROL
     *
     * @mbggenerated
     */
    public Boolean getParallelcontrol() {
        return parallelcontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.PARALLELCONTROL
     *
     * @param parallelcontrol the value for FCT_WORKGUIDESTAGE.PARALLELCONTROL
     *
     * @mbggenerated
     */
    public void setParallelcontrol(Boolean parallelcontrol) {
        this.parallelcontrol = parallelcontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.QCCAUSEOFREWORKCONTROLLER
     *
     * @return the value of FCT_WORKGUIDESTAGE.QCCAUSEOFREWORKCONTROLLER
     *
     * @mbggenerated
     */
    public Boolean getQccauseofreworkcontroller() {
        return qccauseofreworkcontroller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.QCCAUSEOFREWORKCONTROLLER
     *
     * @param qccauseofreworkcontroller the value for FCT_WORKGUIDESTAGE.QCCAUSEOFREWORKCONTROLLER
     *
     * @mbggenerated
     */
    public void setQccauseofreworkcontroller(Boolean qccauseofreworkcontroller) {
        this.qccauseofreworkcontroller = qccauseofreworkcontroller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.QCCAUSEOFSCRPCONTROLLER
     *
     * @return the value of FCT_WORKGUIDESTAGE.QCCAUSEOFSCRPCONTROLLER
     *
     * @mbggenerated
     */
    public Boolean getQccauseofscrpcontroller() {
        return qccauseofscrpcontroller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.QCCAUSEOFSCRPCONTROLLER
     *
     * @param qccauseofscrpcontroller the value for FCT_WORKGUIDESTAGE.QCCAUSEOFSCRPCONTROLLER
     *
     * @mbggenerated
     */
    public void setQccauseofscrpcontroller(Boolean qccauseofscrpcontroller) {
        this.qccauseofscrpcontroller = qccauseofscrpcontroller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.QCCAUSEOFREJECTCONTROLLER
     *
     * @return the value of FCT_WORKGUIDESTAGE.QCCAUSEOFREJECTCONTROLLER
     *
     * @mbggenerated
     */
    public Boolean getQccauseofrejectcontroller() {
        return qccauseofrejectcontroller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.QCCAUSEOFREJECTCONTROLLER
     *
     * @param qccauseofrejectcontroller the value for FCT_WORKGUIDESTAGE.QCCAUSEOFREJECTCONTROLLER
     *
     * @mbggenerated
     */
    public void setQccauseofrejectcontroller(Boolean qccauseofrejectcontroller) {
        this.qccauseofrejectcontroller = qccauseofrejectcontroller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.PERIOD
     *
     * @return the value of FCT_WORKGUIDESTAGE.PERIOD
     *
     * @mbggenerated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.PERIOD
     *
     * @param period the value for FCT_WORKGUIDESTAGE.PERIOD
     *
     * @mbggenerated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.BASEPERIOD
     *
     * @return the value of FCT_WORKGUIDESTAGE.BASEPERIOD
     *
     * @mbggenerated
     */
    public Integer getBaseperiod() {
        return baseperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.BASEPERIOD
     *
     * @param baseperiod the value for FCT_WORKGUIDESTAGE.BASEPERIOD
     *
     * @mbggenerated
     */
    public void setBaseperiod(Integer baseperiod) {
        this.baseperiod = baseperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.PERIODTYPE
     *
     * @return the value of FCT_WORKGUIDESTAGE.PERIODTYPE
     *
     * @mbggenerated
     */
    public Integer getPeriodtype() {
        return periodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.PERIODTYPE
     *
     * @param periodtype the value for FCT_WORKGUIDESTAGE.PERIODTYPE
     *
     * @mbggenerated
     */
    public void setPeriodtype(Integer periodtype) {
        this.periodtype = periodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.TRANSFERBATCH
     *
     * @return the value of FCT_WORKGUIDESTAGE.TRANSFERBATCH
     *
     * @mbggenerated
     */
    public Integer getTransferbatch() {
        return transferbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.TRANSFERBATCH
     *
     * @param transferbatch the value for FCT_WORKGUIDESTAGE.TRANSFERBATCH
     *
     * @mbggenerated
     */
    public void setTransferbatch(Integer transferbatch) {
        this.transferbatch = transferbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDESTAGE.WAITINGTIME
     *
     * @return the value of FCT_WORKGUIDESTAGE.WAITINGTIME
     *
     * @mbggenerated
     */
    public BigDecimal getWaitingtime() {
        return waitingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDESTAGE.WAITINGTIME
     *
     * @param waitingtime the value for FCT_WORKGUIDESTAGE.WAITINGTIME
     *
     * @mbggenerated
     */
    public void setWaitingtime(BigDecimal waitingtime) {
        this.waitingtime = waitingtime;
    }
}