package com.debug.mybatis.entity;

import java.math.BigDecimal;

public class FctWorkguide {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.AUTOID
     *
     * @mbggenerated
     */
    private Long autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SYS_ORG
     *
     * @mbggenerated
     */
    private Long sysOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    private String sysCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    private String sysModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SYS_CREATOR
     *
     * @mbggenerated
     */
    private String sysCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SYS_MODIFIER
     *
     * @mbggenerated
     */
    private String sysModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.FLAG
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.IDEFINE1
     *
     * @mbggenerated
     */
    private Integer idefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.IDEFINE2
     *
     * @mbggenerated
     */
    private Integer idefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.IDEFINE3
     *
     * @mbggenerated
     */
    private Integer idefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.IDEFINE4
     *
     * @mbggenerated
     */
    private Integer idefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.IDEFINE5
     *
     * @mbggenerated
     */
    private Integer idefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.FDEFINE1
     *
     * @mbggenerated
     */
    private Double fdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.FDEFINE2
     *
     * @mbggenerated
     */
    private Double fdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.FDEFINE3
     *
     * @mbggenerated
     */
    private Double fdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.FDEFINE4
     *
     * @mbggenerated
     */
    private Double fdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.FDEFINE5
     *
     * @mbggenerated
     */
    private Double fdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SDEFINE1
     *
     * @mbggenerated
     */
    private String sdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SDEFINE2
     *
     * @mbggenerated
     */
    private String sdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SDEFINE3
     *
     * @mbggenerated
     */
    private String sdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SDEFINE4
     *
     * @mbggenerated
     */
    private String sdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SDEFINE5
     *
     * @mbggenerated
     */
    private String sdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.ATTACH
     *
     * @mbggenerated
     */
    private Long attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.MO
     *
     * @mbggenerated
     */
    private Long mo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.MOCODE
     *
     * @mbggenerated
     */
    private String mocode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.PART
     *
     * @mbggenerated
     */
    private Long part;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.PARTCODE
     *
     * @mbggenerated
     */
    private String partcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.PARTNAME
     *
     * @mbggenerated
     */
    private String partname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.PARTSTD
     *
     * @mbggenerated
     */
    private String partstd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.ROUTINGMAIN
     *
     * @mbggenerated
     */
    private Long routingmain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.QTY
     *
     * @mbggenerated
     */
    private BigDecimal qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.OPENDATE
     *
     * @mbggenerated
     */
    private String opendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.DUEDATE
     *
     * @mbggenerated
     */
    private String duedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.TRACECODE
     *
     * @mbggenerated
     */
    private String tracecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.ACCURACY
     *
     * @mbggenerated
     */
    private Integer accuracy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.ROUTINGVER
     *
     * @mbggenerated
     */
    private String routingver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.PRIORITY
     *
     * @mbggenerated
     */
    private Long priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.SALESPRIORITY
     *
     * @mbggenerated
     */
    private Integer salespriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.PMCSORT
     *
     * @mbggenerated
     */
    private Integer pmcsort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.PLANSTARTTIME
     *
     * @mbggenerated
     */
    private String planstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FCT_WORKGUIDE.PLANENDTIME
     *
     * @mbggenerated
     */
    private String planendtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.AUTOID
     *
     * @return the value of FCT_WORKGUIDE.AUTOID
     *
     * @mbggenerated
     */
    public Long getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.AUTOID
     *
     * @param autoid the value for FCT_WORKGUIDE.AUTOID
     *
     * @mbggenerated
     */
    public void setAutoid(Long autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SYS_ORG
     *
     * @return the value of FCT_WORKGUIDE.SYS_ORG
     *
     * @mbggenerated
     */
    public Long getSysOrg() {
        return sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SYS_ORG
     *
     * @param sysOrg the value for FCT_WORKGUIDE.SYS_ORG
     *
     * @mbggenerated
     */
    public void setSysOrg(Long sysOrg) {
        this.sysOrg = sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SYS_CREATE_DATE
     *
     * @return the value of FCT_WORKGUIDE.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public String getSysCreateDate() {
        return sysCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SYS_CREATE_DATE
     *
     * @param sysCreateDate the value for FCT_WORKGUIDE.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setSysCreateDate(String sysCreateDate) {
        this.sysCreateDate = sysCreateDate == null ? null : sysCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SYS_MODIFY_DATE
     *
     * @return the value of FCT_WORKGUIDE.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public String getSysModifyDate() {
        return sysModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SYS_MODIFY_DATE
     *
     * @param sysModifyDate the value for FCT_WORKGUIDE.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setSysModifyDate(String sysModifyDate) {
        this.sysModifyDate = sysModifyDate == null ? null : sysModifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SYS_CREATOR
     *
     * @return the value of FCT_WORKGUIDE.SYS_CREATOR
     *
     * @mbggenerated
     */
    public String getSysCreator() {
        return sysCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SYS_CREATOR
     *
     * @param sysCreator the value for FCT_WORKGUIDE.SYS_CREATOR
     *
     * @mbggenerated
     */
    public void setSysCreator(String sysCreator) {
        this.sysCreator = sysCreator == null ? null : sysCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SYS_MODIFIER
     *
     * @return the value of FCT_WORKGUIDE.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public String getSysModifier() {
        return sysModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SYS_MODIFIER
     *
     * @param sysModifier the value for FCT_WORKGUIDE.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public void setSysModifier(String sysModifier) {
        this.sysModifier = sysModifier == null ? null : sysModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.FLAG
     *
     * @return the value of FCT_WORKGUIDE.FLAG
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.FLAG
     *
     * @param flag the value for FCT_WORKGUIDE.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.IDEFINE1
     *
     * @return the value of FCT_WORKGUIDE.IDEFINE1
     *
     * @mbggenerated
     */
    public Integer getIdefine1() {
        return idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.IDEFINE1
     *
     * @param idefine1 the value for FCT_WORKGUIDE.IDEFINE1
     *
     * @mbggenerated
     */
    public void setIdefine1(Integer idefine1) {
        this.idefine1 = idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.IDEFINE2
     *
     * @return the value of FCT_WORKGUIDE.IDEFINE2
     *
     * @mbggenerated
     */
    public Integer getIdefine2() {
        return idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.IDEFINE2
     *
     * @param idefine2 the value for FCT_WORKGUIDE.IDEFINE2
     *
     * @mbggenerated
     */
    public void setIdefine2(Integer idefine2) {
        this.idefine2 = idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.IDEFINE3
     *
     * @return the value of FCT_WORKGUIDE.IDEFINE3
     *
     * @mbggenerated
     */
    public Integer getIdefine3() {
        return idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.IDEFINE3
     *
     * @param idefine3 the value for FCT_WORKGUIDE.IDEFINE3
     *
     * @mbggenerated
     */
    public void setIdefine3(Integer idefine3) {
        this.idefine3 = idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.IDEFINE4
     *
     * @return the value of FCT_WORKGUIDE.IDEFINE4
     *
     * @mbggenerated
     */
    public Integer getIdefine4() {
        return idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.IDEFINE4
     *
     * @param idefine4 the value for FCT_WORKGUIDE.IDEFINE4
     *
     * @mbggenerated
     */
    public void setIdefine4(Integer idefine4) {
        this.idefine4 = idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.IDEFINE5
     *
     * @return the value of FCT_WORKGUIDE.IDEFINE5
     *
     * @mbggenerated
     */
    public Integer getIdefine5() {
        return idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.IDEFINE5
     *
     * @param idefine5 the value for FCT_WORKGUIDE.IDEFINE5
     *
     * @mbggenerated
     */
    public void setIdefine5(Integer idefine5) {
        this.idefine5 = idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.FDEFINE1
     *
     * @return the value of FCT_WORKGUIDE.FDEFINE1
     *
     * @mbggenerated
     */
    public Double getFdefine1() {
        return fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.FDEFINE1
     *
     * @param fdefine1 the value for FCT_WORKGUIDE.FDEFINE1
     *
     * @mbggenerated
     */
    public void setFdefine1(Double fdefine1) {
        this.fdefine1 = fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.FDEFINE2
     *
     * @return the value of FCT_WORKGUIDE.FDEFINE2
     *
     * @mbggenerated
     */
    public Double getFdefine2() {
        return fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.FDEFINE2
     *
     * @param fdefine2 the value for FCT_WORKGUIDE.FDEFINE2
     *
     * @mbggenerated
     */
    public void setFdefine2(Double fdefine2) {
        this.fdefine2 = fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.FDEFINE3
     *
     * @return the value of FCT_WORKGUIDE.FDEFINE3
     *
     * @mbggenerated
     */
    public Double getFdefine3() {
        return fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.FDEFINE3
     *
     * @param fdefine3 the value for FCT_WORKGUIDE.FDEFINE3
     *
     * @mbggenerated
     */
    public void setFdefine3(Double fdefine3) {
        this.fdefine3 = fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.FDEFINE4
     *
     * @return the value of FCT_WORKGUIDE.FDEFINE4
     *
     * @mbggenerated
     */
    public Double getFdefine4() {
        return fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.FDEFINE4
     *
     * @param fdefine4 the value for FCT_WORKGUIDE.FDEFINE4
     *
     * @mbggenerated
     */
    public void setFdefine4(Double fdefine4) {
        this.fdefine4 = fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.FDEFINE5
     *
     * @return the value of FCT_WORKGUIDE.FDEFINE5
     *
     * @mbggenerated
     */
    public Double getFdefine5() {
        return fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.FDEFINE5
     *
     * @param fdefine5 the value for FCT_WORKGUIDE.FDEFINE5
     *
     * @mbggenerated
     */
    public void setFdefine5(Double fdefine5) {
        this.fdefine5 = fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SDEFINE1
     *
     * @return the value of FCT_WORKGUIDE.SDEFINE1
     *
     * @mbggenerated
     */
    public String getSdefine1() {
        return sdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SDEFINE1
     *
     * @param sdefine1 the value for FCT_WORKGUIDE.SDEFINE1
     *
     * @mbggenerated
     */
    public void setSdefine1(String sdefine1) {
        this.sdefine1 = sdefine1 == null ? null : sdefine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SDEFINE2
     *
     * @return the value of FCT_WORKGUIDE.SDEFINE2
     *
     * @mbggenerated
     */
    public String getSdefine2() {
        return sdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SDEFINE2
     *
     * @param sdefine2 the value for FCT_WORKGUIDE.SDEFINE2
     *
     * @mbggenerated
     */
    public void setSdefine2(String sdefine2) {
        this.sdefine2 = sdefine2 == null ? null : sdefine2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SDEFINE3
     *
     * @return the value of FCT_WORKGUIDE.SDEFINE3
     *
     * @mbggenerated
     */
    public String getSdefine3() {
        return sdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SDEFINE3
     *
     * @param sdefine3 the value for FCT_WORKGUIDE.SDEFINE3
     *
     * @mbggenerated
     */
    public void setSdefine3(String sdefine3) {
        this.sdefine3 = sdefine3 == null ? null : sdefine3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SDEFINE4
     *
     * @return the value of FCT_WORKGUIDE.SDEFINE4
     *
     * @mbggenerated
     */
    public String getSdefine4() {
        return sdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SDEFINE4
     *
     * @param sdefine4 the value for FCT_WORKGUIDE.SDEFINE4
     *
     * @mbggenerated
     */
    public void setSdefine4(String sdefine4) {
        this.sdefine4 = sdefine4 == null ? null : sdefine4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SDEFINE5
     *
     * @return the value of FCT_WORKGUIDE.SDEFINE5
     *
     * @mbggenerated
     */
    public String getSdefine5() {
        return sdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SDEFINE5
     *
     * @param sdefine5 the value for FCT_WORKGUIDE.SDEFINE5
     *
     * @mbggenerated
     */
    public void setSdefine5(String sdefine5) {
        this.sdefine5 = sdefine5 == null ? null : sdefine5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.ATTACH
     *
     * @return the value of FCT_WORKGUIDE.ATTACH
     *
     * @mbggenerated
     */
    public Long getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.ATTACH
     *
     * @param attach the value for FCT_WORKGUIDE.ATTACH
     *
     * @mbggenerated
     */
    public void setAttach(Long attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.MO
     *
     * @return the value of FCT_WORKGUIDE.MO
     *
     * @mbggenerated
     */
    public Long getMo() {
        return mo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.MO
     *
     * @param mo the value for FCT_WORKGUIDE.MO
     *
     * @mbggenerated
     */
    public void setMo(Long mo) {
        this.mo = mo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.MOCODE
     *
     * @return the value of FCT_WORKGUIDE.MOCODE
     *
     * @mbggenerated
     */
    public String getMocode() {
        return mocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.MOCODE
     *
     * @param mocode the value for FCT_WORKGUIDE.MOCODE
     *
     * @mbggenerated
     */
    public void setMocode(String mocode) {
        this.mocode = mocode == null ? null : mocode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.PART
     *
     * @return the value of FCT_WORKGUIDE.PART
     *
     * @mbggenerated
     */
    public Long getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.PART
     *
     * @param part the value for FCT_WORKGUIDE.PART
     *
     * @mbggenerated
     */
    public void setPart(Long part) {
        this.part = part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.PARTCODE
     *
     * @return the value of FCT_WORKGUIDE.PARTCODE
     *
     * @mbggenerated
     */
    public String getPartcode() {
        return partcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.PARTCODE
     *
     * @param partcode the value for FCT_WORKGUIDE.PARTCODE
     *
     * @mbggenerated
     */
    public void setPartcode(String partcode) {
        this.partcode = partcode == null ? null : partcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.PARTNAME
     *
     * @return the value of FCT_WORKGUIDE.PARTNAME
     *
     * @mbggenerated
     */
    public String getPartname() {
        return partname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.PARTNAME
     *
     * @param partname the value for FCT_WORKGUIDE.PARTNAME
     *
     * @mbggenerated
     */
    public void setPartname(String partname) {
        this.partname = partname == null ? null : partname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.PARTSTD
     *
     * @return the value of FCT_WORKGUIDE.PARTSTD
     *
     * @mbggenerated
     */
    public String getPartstd() {
        return partstd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.PARTSTD
     *
     * @param partstd the value for FCT_WORKGUIDE.PARTSTD
     *
     * @mbggenerated
     */
    public void setPartstd(String partstd) {
        this.partstd = partstd == null ? null : partstd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.UNIT
     *
     * @return the value of FCT_WORKGUIDE.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.UNIT
     *
     * @param unit the value for FCT_WORKGUIDE.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.ROUTINGMAIN
     *
     * @return the value of FCT_WORKGUIDE.ROUTINGMAIN
     *
     * @mbggenerated
     */
    public Long getRoutingmain() {
        return routingmain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.ROUTINGMAIN
     *
     * @param routingmain the value for FCT_WORKGUIDE.ROUTINGMAIN
     *
     * @mbggenerated
     */
    public void setRoutingmain(Long routingmain) {
        this.routingmain = routingmain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.QTY
     *
     * @return the value of FCT_WORKGUIDE.QTY
     *
     * @mbggenerated
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.QTY
     *
     * @param qty the value for FCT_WORKGUIDE.QTY
     *
     * @mbggenerated
     */
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.OPENDATE
     *
     * @return the value of FCT_WORKGUIDE.OPENDATE
     *
     * @mbggenerated
     */
    public String getOpendate() {
        return opendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.OPENDATE
     *
     * @param opendate the value for FCT_WORKGUIDE.OPENDATE
     *
     * @mbggenerated
     */
    public void setOpendate(String opendate) {
        this.opendate = opendate == null ? null : opendate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.DUEDATE
     *
     * @return the value of FCT_WORKGUIDE.DUEDATE
     *
     * @mbggenerated
     */
    public String getDuedate() {
        return duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.DUEDATE
     *
     * @param duedate the value for FCT_WORKGUIDE.DUEDATE
     *
     * @mbggenerated
     */
    public void setDuedate(String duedate) {
        this.duedate = duedate == null ? null : duedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.TRACECODE
     *
     * @return the value of FCT_WORKGUIDE.TRACECODE
     *
     * @mbggenerated
     */
    public String getTracecode() {
        return tracecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.TRACECODE
     *
     * @param tracecode the value for FCT_WORKGUIDE.TRACECODE
     *
     * @mbggenerated
     */
    public void setTracecode(String tracecode) {
        this.tracecode = tracecode == null ? null : tracecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.ACCURACY
     *
     * @return the value of FCT_WORKGUIDE.ACCURACY
     *
     * @mbggenerated
     */
    public Integer getAccuracy() {
        return accuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.ACCURACY
     *
     * @param accuracy the value for FCT_WORKGUIDE.ACCURACY
     *
     * @mbggenerated
     */
    public void setAccuracy(Integer accuracy) {
        this.accuracy = accuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.ROUTINGVER
     *
     * @return the value of FCT_WORKGUIDE.ROUTINGVER
     *
     * @mbggenerated
     */
    public String getRoutingver() {
        return routingver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.ROUTINGVER
     *
     * @param routingver the value for FCT_WORKGUIDE.ROUTINGVER
     *
     * @mbggenerated
     */
    public void setRoutingver(String routingver) {
        this.routingver = routingver == null ? null : routingver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.PRIORITY
     *
     * @return the value of FCT_WORKGUIDE.PRIORITY
     *
     * @mbggenerated
     */
    public Long getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.PRIORITY
     *
     * @param priority the value for FCT_WORKGUIDE.PRIORITY
     *
     * @mbggenerated
     */
    public void setPriority(Long priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.SALESPRIORITY
     *
     * @return the value of FCT_WORKGUIDE.SALESPRIORITY
     *
     * @mbggenerated
     */
    public Integer getSalespriority() {
        return salespriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.SALESPRIORITY
     *
     * @param salespriority the value for FCT_WORKGUIDE.SALESPRIORITY
     *
     * @mbggenerated
     */
    public void setSalespriority(Integer salespriority) {
        this.salespriority = salespriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.PMCSORT
     *
     * @return the value of FCT_WORKGUIDE.PMCSORT
     *
     * @mbggenerated
     */
    public Integer getPmcsort() {
        return pmcsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.PMCSORT
     *
     * @param pmcsort the value for FCT_WORKGUIDE.PMCSORT
     *
     * @mbggenerated
     */
    public void setPmcsort(Integer pmcsort) {
        this.pmcsort = pmcsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.PLANSTARTTIME
     *
     * @return the value of FCT_WORKGUIDE.PLANSTARTTIME
     *
     * @mbggenerated
     */
    public String getPlanstarttime() {
        return planstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.PLANSTARTTIME
     *
     * @param planstarttime the value for FCT_WORKGUIDE.PLANSTARTTIME
     *
     * @mbggenerated
     */
    public void setPlanstarttime(String planstarttime) {
        this.planstarttime = planstarttime == null ? null : planstarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FCT_WORKGUIDE.PLANENDTIME
     *
     * @return the value of FCT_WORKGUIDE.PLANENDTIME
     *
     * @mbggenerated
     */
    public String getPlanendtime() {
        return planendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FCT_WORKGUIDE.PLANENDTIME
     *
     * @param planendtime the value for FCT_WORKGUIDE.PLANENDTIME
     *
     * @mbggenerated
     */
    public void setPlanendtime(String planendtime) {
        this.planendtime = planendtime == null ? null : planendtime.trim();
    }
}