package com.debug.mybatis.entity;

import java.math.BigDecimal;

public class OrgExzone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.AUTOID
     *
     * @mbggenerated
     */
    private Long autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SYS_ORG
     *
     * @mbggenerated
     */
    private Long sysOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    private String sysCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    private String sysModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SYS_CREATOR
     *
     * @mbggenerated
     */
    private String sysCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SYS_MODIFIER
     *
     * @mbggenerated
     */
    private String sysModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.FLAG
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.IDEFINE1
     *
     * @mbggenerated
     */
    private Integer idefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.IDEFINE2
     *
     * @mbggenerated
     */
    private Integer idefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.IDEFINE3
     *
     * @mbggenerated
     */
    private Integer idefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.IDEFINE4
     *
     * @mbggenerated
     */
    private Integer idefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.IDEFINE5
     *
     * @mbggenerated
     */
    private Integer idefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.FDEFINE1
     *
     * @mbggenerated
     */
    private Double fdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.FDEFINE2
     *
     * @mbggenerated
     */
    private Double fdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.FDEFINE3
     *
     * @mbggenerated
     */
    private Double fdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.FDEFINE4
     *
     * @mbggenerated
     */
    private Double fdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.FDEFINE5
     *
     * @mbggenerated
     */
    private Double fdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SDEFINE1
     *
     * @mbggenerated
     */
    private String sdefine1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SDEFINE2
     *
     * @mbggenerated
     */
    private String sdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SDEFINE3
     *
     * @mbggenerated
     */
    private String sdefine3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SDEFINE4
     *
     * @mbggenerated
     */
    private String sdefine4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.SDEFINE5
     *
     * @mbggenerated
     */
    private String sdefine5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.ATTACH
     *
     * @mbggenerated
     */
    private Long attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.CONTROLLOR
     *
     * @mbggenerated
     */
    private Boolean controllor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.AUTODISTRIBUTED
     *
     * @mbggenerated
     */
    private Boolean autodistributed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.MANAGER
     *
     * @mbggenerated
     */
    private Long manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.WORKUNIT
     *
     * @mbggenerated
     */
    private Long workunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.IFMERGEWARN
     *
     * @mbggenerated
     */
    private Boolean ifmergewarn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.WARNTIME
     *
     * @mbggenerated
     */
    private BigDecimal warntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORG_EXZONE.WARNMIN
     *
     * @mbggenerated
     */
    private BigDecimal warnmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.AUTOID
     *
     * @return the value of ORG_EXZONE.AUTOID
     *
     * @mbggenerated
     */
    public Long getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.AUTOID
     *
     * @param autoid the value for ORG_EXZONE.AUTOID
     *
     * @mbggenerated
     */
    public void setAutoid(Long autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SYS_ORG
     *
     * @return the value of ORG_EXZONE.SYS_ORG
     *
     * @mbggenerated
     */
    public Long getSysOrg() {
        return sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SYS_ORG
     *
     * @param sysOrg the value for ORG_EXZONE.SYS_ORG
     *
     * @mbggenerated
     */
    public void setSysOrg(Long sysOrg) {
        this.sysOrg = sysOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SYS_CREATE_DATE
     *
     * @return the value of ORG_EXZONE.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public String getSysCreateDate() {
        return sysCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SYS_CREATE_DATE
     *
     * @param sysCreateDate the value for ORG_EXZONE.SYS_CREATE_DATE
     *
     * @mbggenerated
     */
    public void setSysCreateDate(String sysCreateDate) {
        this.sysCreateDate = sysCreateDate == null ? null : sysCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SYS_MODIFY_DATE
     *
     * @return the value of ORG_EXZONE.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public String getSysModifyDate() {
        return sysModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SYS_MODIFY_DATE
     *
     * @param sysModifyDate the value for ORG_EXZONE.SYS_MODIFY_DATE
     *
     * @mbggenerated
     */
    public void setSysModifyDate(String sysModifyDate) {
        this.sysModifyDate = sysModifyDate == null ? null : sysModifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SYS_CREATOR
     *
     * @return the value of ORG_EXZONE.SYS_CREATOR
     *
     * @mbggenerated
     */
    public String getSysCreator() {
        return sysCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SYS_CREATOR
     *
     * @param sysCreator the value for ORG_EXZONE.SYS_CREATOR
     *
     * @mbggenerated
     */
    public void setSysCreator(String sysCreator) {
        this.sysCreator = sysCreator == null ? null : sysCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SYS_MODIFIER
     *
     * @return the value of ORG_EXZONE.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public String getSysModifier() {
        return sysModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SYS_MODIFIER
     *
     * @param sysModifier the value for ORG_EXZONE.SYS_MODIFIER
     *
     * @mbggenerated
     */
    public void setSysModifier(String sysModifier) {
        this.sysModifier = sysModifier == null ? null : sysModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.FLAG
     *
     * @return the value of ORG_EXZONE.FLAG
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.FLAG
     *
     * @param flag the value for ORG_EXZONE.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.IDEFINE1
     *
     * @return the value of ORG_EXZONE.IDEFINE1
     *
     * @mbggenerated
     */
    public Integer getIdefine1() {
        return idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.IDEFINE1
     *
     * @param idefine1 the value for ORG_EXZONE.IDEFINE1
     *
     * @mbggenerated
     */
    public void setIdefine1(Integer idefine1) {
        this.idefine1 = idefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.IDEFINE2
     *
     * @return the value of ORG_EXZONE.IDEFINE2
     *
     * @mbggenerated
     */
    public Integer getIdefine2() {
        return idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.IDEFINE2
     *
     * @param idefine2 the value for ORG_EXZONE.IDEFINE2
     *
     * @mbggenerated
     */
    public void setIdefine2(Integer idefine2) {
        this.idefine2 = idefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.IDEFINE3
     *
     * @return the value of ORG_EXZONE.IDEFINE3
     *
     * @mbggenerated
     */
    public Integer getIdefine3() {
        return idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.IDEFINE3
     *
     * @param idefine3 the value for ORG_EXZONE.IDEFINE3
     *
     * @mbggenerated
     */
    public void setIdefine3(Integer idefine3) {
        this.idefine3 = idefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.IDEFINE4
     *
     * @return the value of ORG_EXZONE.IDEFINE4
     *
     * @mbggenerated
     */
    public Integer getIdefine4() {
        return idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.IDEFINE4
     *
     * @param idefine4 the value for ORG_EXZONE.IDEFINE4
     *
     * @mbggenerated
     */
    public void setIdefine4(Integer idefine4) {
        this.idefine4 = idefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.IDEFINE5
     *
     * @return the value of ORG_EXZONE.IDEFINE5
     *
     * @mbggenerated
     */
    public Integer getIdefine5() {
        return idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.IDEFINE5
     *
     * @param idefine5 the value for ORG_EXZONE.IDEFINE5
     *
     * @mbggenerated
     */
    public void setIdefine5(Integer idefine5) {
        this.idefine5 = idefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.FDEFINE1
     *
     * @return the value of ORG_EXZONE.FDEFINE1
     *
     * @mbggenerated
     */
    public Double getFdefine1() {
        return fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.FDEFINE1
     *
     * @param fdefine1 the value for ORG_EXZONE.FDEFINE1
     *
     * @mbggenerated
     */
    public void setFdefine1(Double fdefine1) {
        this.fdefine1 = fdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.FDEFINE2
     *
     * @return the value of ORG_EXZONE.FDEFINE2
     *
     * @mbggenerated
     */
    public Double getFdefine2() {
        return fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.FDEFINE2
     *
     * @param fdefine2 the value for ORG_EXZONE.FDEFINE2
     *
     * @mbggenerated
     */
    public void setFdefine2(Double fdefine2) {
        this.fdefine2 = fdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.FDEFINE3
     *
     * @return the value of ORG_EXZONE.FDEFINE3
     *
     * @mbggenerated
     */
    public Double getFdefine3() {
        return fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.FDEFINE3
     *
     * @param fdefine3 the value for ORG_EXZONE.FDEFINE3
     *
     * @mbggenerated
     */
    public void setFdefine3(Double fdefine3) {
        this.fdefine3 = fdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.FDEFINE4
     *
     * @return the value of ORG_EXZONE.FDEFINE4
     *
     * @mbggenerated
     */
    public Double getFdefine4() {
        return fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.FDEFINE4
     *
     * @param fdefine4 the value for ORG_EXZONE.FDEFINE4
     *
     * @mbggenerated
     */
    public void setFdefine4(Double fdefine4) {
        this.fdefine4 = fdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.FDEFINE5
     *
     * @return the value of ORG_EXZONE.FDEFINE5
     *
     * @mbggenerated
     */
    public Double getFdefine5() {
        return fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.FDEFINE5
     *
     * @param fdefine5 the value for ORG_EXZONE.FDEFINE5
     *
     * @mbggenerated
     */
    public void setFdefine5(Double fdefine5) {
        this.fdefine5 = fdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SDEFINE1
     *
     * @return the value of ORG_EXZONE.SDEFINE1
     *
     * @mbggenerated
     */
    public String getSdefine1() {
        return sdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SDEFINE1
     *
     * @param sdefine1 the value for ORG_EXZONE.SDEFINE1
     *
     * @mbggenerated
     */
    public void setSdefine1(String sdefine1) {
        this.sdefine1 = sdefine1 == null ? null : sdefine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SDEFINE2
     *
     * @return the value of ORG_EXZONE.SDEFINE2
     *
     * @mbggenerated
     */
    public String getSdefine2() {
        return sdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SDEFINE2
     *
     * @param sdefine2 the value for ORG_EXZONE.SDEFINE2
     *
     * @mbggenerated
     */
    public void setSdefine2(String sdefine2) {
        this.sdefine2 = sdefine2 == null ? null : sdefine2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SDEFINE3
     *
     * @return the value of ORG_EXZONE.SDEFINE3
     *
     * @mbggenerated
     */
    public String getSdefine3() {
        return sdefine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SDEFINE3
     *
     * @param sdefine3 the value for ORG_EXZONE.SDEFINE3
     *
     * @mbggenerated
     */
    public void setSdefine3(String sdefine3) {
        this.sdefine3 = sdefine3 == null ? null : sdefine3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SDEFINE4
     *
     * @return the value of ORG_EXZONE.SDEFINE4
     *
     * @mbggenerated
     */
    public String getSdefine4() {
        return sdefine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SDEFINE4
     *
     * @param sdefine4 the value for ORG_EXZONE.SDEFINE4
     *
     * @mbggenerated
     */
    public void setSdefine4(String sdefine4) {
        this.sdefine4 = sdefine4 == null ? null : sdefine4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.SDEFINE5
     *
     * @return the value of ORG_EXZONE.SDEFINE5
     *
     * @mbggenerated
     */
    public String getSdefine5() {
        return sdefine5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.SDEFINE5
     *
     * @param sdefine5 the value for ORG_EXZONE.SDEFINE5
     *
     * @mbggenerated
     */
    public void setSdefine5(String sdefine5) {
        this.sdefine5 = sdefine5 == null ? null : sdefine5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.ATTACH
     *
     * @return the value of ORG_EXZONE.ATTACH
     *
     * @mbggenerated
     */
    public Long getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.ATTACH
     *
     * @param attach the value for ORG_EXZONE.ATTACH
     *
     * @mbggenerated
     */
    public void setAttach(Long attach) {
        this.attach = attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.CODE
     *
     * @return the value of ORG_EXZONE.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.CODE
     *
     * @param code the value for ORG_EXZONE.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.NAME
     *
     * @return the value of ORG_EXZONE.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.NAME
     *
     * @param name the value for ORG_EXZONE.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.CONTROLLOR
     *
     * @return the value of ORG_EXZONE.CONTROLLOR
     *
     * @mbggenerated
     */
    public Boolean getControllor() {
        return controllor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.CONTROLLOR
     *
     * @param controllor the value for ORG_EXZONE.CONTROLLOR
     *
     * @mbggenerated
     */
    public void setControllor(Boolean controllor) {
        this.controllor = controllor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.AUTODISTRIBUTED
     *
     * @return the value of ORG_EXZONE.AUTODISTRIBUTED
     *
     * @mbggenerated
     */
    public Boolean getAutodistributed() {
        return autodistributed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.AUTODISTRIBUTED
     *
     * @param autodistributed the value for ORG_EXZONE.AUTODISTRIBUTED
     *
     * @mbggenerated
     */
    public void setAutodistributed(Boolean autodistributed) {
        this.autodistributed = autodistributed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.MANAGER
     *
     * @return the value of ORG_EXZONE.MANAGER
     *
     * @mbggenerated
     */
    public Long getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.MANAGER
     *
     * @param manager the value for ORG_EXZONE.MANAGER
     *
     * @mbggenerated
     */
    public void setManager(Long manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.WORKUNIT
     *
     * @return the value of ORG_EXZONE.WORKUNIT
     *
     * @mbggenerated
     */
    public Long getWorkunit() {
        return workunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.WORKUNIT
     *
     * @param workunit the value for ORG_EXZONE.WORKUNIT
     *
     * @mbggenerated
     */
    public void setWorkunit(Long workunit) {
        this.workunit = workunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.IFMERGEWARN
     *
     * @return the value of ORG_EXZONE.IFMERGEWARN
     *
     * @mbggenerated
     */
    public Boolean getIfmergewarn() {
        return ifmergewarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.IFMERGEWARN
     *
     * @param ifmergewarn the value for ORG_EXZONE.IFMERGEWARN
     *
     * @mbggenerated
     */
    public void setIfmergewarn(Boolean ifmergewarn) {
        this.ifmergewarn = ifmergewarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.WARNTIME
     *
     * @return the value of ORG_EXZONE.WARNTIME
     *
     * @mbggenerated
     */
    public BigDecimal getWarntime() {
        return warntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.WARNTIME
     *
     * @param warntime the value for ORG_EXZONE.WARNTIME
     *
     * @mbggenerated
     */
    public void setWarntime(BigDecimal warntime) {
        this.warntime = warntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORG_EXZONE.WARNMIN
     *
     * @return the value of ORG_EXZONE.WARNMIN
     *
     * @mbggenerated
     */
    public BigDecimal getWarnmin() {
        return warnmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORG_EXZONE.WARNMIN
     *
     * @param warnmin the value for ORG_EXZONE.WARNMIN
     *
     * @mbggenerated
     */
    public void setWarnmin(BigDecimal warnmin) {
        this.warnmin = warnmin;
    }
}