server:
  port: 8100
spring:
  application:
    name: client-consumer-cluster
eureka:
  instance:
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://debug:12321@localhost:8000/eureka,http://debug:12321@localhost:8001/eureka,http://debug:12321@localhost:8002/eureka